[short="Testimony of Upper Evesham Monthly Meeting"]
== A Testimony of the Monthly Meeting of Upper Evesham, New Jersey, Concerning our Beloved Friend, Elizabeth Collins, Deceased.

This our dear friend was born the 4th of the first month, 1755; her parents,
Joshua and Naomi Ballinger, being members of our religious Society.
It appears by her own account left in writing,
that her father died soon after she was six years of age;
which notwithstanding the care of a watchful and affectionate mother,
subjected her to many trials and difficulties.
But she found her gracious Helper to be near, although like Samuel,
when called of the Lord, she knew not what it was that then tendered her mind,
causing her at times to wet her pillow with her tears.
But yielding in measure to this divine influence,
she experienced the supporting arm to be underneath,
and was strengthened to resist many of the temptations incident to youth.

In the eighteenth year of her age, she joined in marriage with John Mason,
a member of Evesham meeting, who, in about four years, was removed by death.
Being thus left with two small children,
under a humbling sense of her afflictions and trials
she was brought very low in body and mind;
but she remarks, "`the Lord in mercy was near to support, and bear up through all,
that I did not sink below hope, but was enabled to put my trust in Him,
who had promised to be with the widow and fatherless.`"

In the year 1778, she was married to our friend Job Collins,
and became a member of Upper Evesham meeting, where,
in the twenty-fourth year of her age, her mind became exercised under an apprehension,
that she was called to bear public testimony therein.
And after a season of deep baptism,
she was enabled to yield obedience to the divine requirings,
by expressing a few words in meeting, which afforded her great peace of mind.
Notwithstanding this, she had often to experience times of close stripping,
when she was ready to call all in question.
But He who regards the sighing of the needy, and satisfies the hungry soul with bread,
condescended in mercy to favour her with the light of his glorious countenance,
to the strength and consolation of her drooping spirit, qualifying her,
as she attended closely to the manifestation of duty,
and persevered in unreserved dedication to the divine Master,
to become a useful instrument,
in publishing the glad tidings of the gospel of our Lord and Saviour Jesus Christ.

As a minister, she was skillful in dividing the word,
labouring zealously in the authority of Truth, to stir up the lukewarm and indifferent,
and speaking a word in season to those that were weary; while the purity of her life,
and the Christian meekness which marked her character,
adorned the doctrines she delivered to others.
In the exercise of the discipline, she was judicious and firm,
being deeply concerned for the maintenance of our religious testimonies.

At different times she was engaged in religious visits
to the meetings of Friends in this,
and some of the adjacent states;
and also in the weighty service of visiting families in various places;
for which service, she appeared to be peculiarly qualified.

The latter years of her life were attended with much bodily indisposition,
but her exertions to meet with her friends in their religious assemblies,
and her humble and reverent deportment, on those solemn occasions,
afforded a striking example to others.

On the decease of several near connections about the same period,
by which she felt much stripped, she expresses herself in the following manner,
"`Although I was thus stripped,
yet I was not forsaken by the Father and Fountain of all our sure mercies,
who in condescending love was pleased to comfort my mind, yes,
to favour with his holy presence.
That I was led humbly to commemorate his goodness,
his love and mercies extended from season to season,
and secretly to implore the continuance of his blessing through time,
that I might not become a dry and withered branch.
O! it is a blessed state to be preserved alive in the Truth,
bringing forth fruits in old age,`" which was remarkably
verified in the experience of this,
our beloved friend, in her advanced life.

In the year 1827, a dispensation of affliction was again allotted to her,
in the painful and protracted illness and death of her beloved husband,
and near the same time in the removal of several of her children.
But through all, her mind was mercifully sustained in resignation,
being enabled to adopt the language; "`Shall not the Judge of all the earth do right?`"

Being greatly exercised on account of the speculation and unsound doctrines and opinions,
that have of late years been disseminated in our Society,
she was often led in her public communications,
to bear a faithful testimony against them;
earnestly asserting her belief in the Lord Jesus as the Saviour of men,
and the only appointed means of salvation.
And a few months previous to her death, she drew up the aforementioned declaration.

After nearly a year`'s confinement through indisposition,
her health was sufficiently improved, in the ninth and tenth months last,
to admit of her again attending our religious meetings.
In those last opportunities of mingling with her friends in solemn worship,
she was remarkably qualified to minister in that divine ability,
for which she had been careful to wait.

In the course of the illness which immediately preceded her final change,
she was preserved in patience and resignation,
manifesting a willingness to fill up her measure of suffering,
often expressing she had no desire respecting the issue of her disease,
and could adopt the language of the apostle, "`For me to live is Christ,
and to die is gain.`"
Her spirit was so clothed with peace and love, that the influence thereof,
gave evidence to those around her,
that she was in measure participating in the joys above.
And as the closing period drew near,
her mind seemed more and more withdrawn from the world,
and under a sense that her work was done, and all would be well,
she appeared as one quietly waiting for the coming of her Lord,
to grant her an admission into the mansions of everlasting rest:
into which we have no doubt, she has been permitted to enter.

She quietly departed this life on the first day of the second month, 1831,
in the seventy-seventh year of her age; having been a minister about fifty-two years:
and on the fourth of the same month her remains were
interred in Friends`' burial ground at Upper Evesham.

The preceding memorial was read and approved by Upper
Evesham Monthly meeting of men and women Friends,
held Third month 12th, 1831, and directed to be signed on behalf thereof, by

[.signed-section-signature]
John N. Reeve,

[.signed-section-signature]
Priscilla W. Reeve, Clerks.

[.signed-section-context-close]
Read and approved in Haddonfield Quarterly meeting.
Third month 17th, 1831.

[.signed-section-closing]
Signed on behalf thereof,

[.signed-section-signature]
David Roberts,

[.signed-section-signature]
Sarah Nicholson, Clerks.
