== Introduction.

These brief memoirs of our late beloved friend,
appear to have been penned for the benefit of her connections, and without expecting,
that they would be made public.
She did not possess the advantages of even a good common school education;
her language is simple,
and though the narrative does not furnish incidents of a very extraordinary character,
yet some of her friends, who had an intimate knowledge of her,
and thence highly esteemed her, believed the publication would be acceptable,
as well as instructive, to the members of her own Society.
Subjected to the exposure, attendant on procuring a livelihood,
at an early period of life, the preservation she witnessed,
is a testimony to the kindness and protection, of the Father of the fatherless.
To those who are deprived of many advantages which others possess in abundance,
it furnishes an incitement to seek an acquaintance with
Him who can amply compensate for all their privations.
From this class, persons eminent for their wisdom and piety, have frequently risen;
and in our own religious community, some of the most serviceable men and women,
in the various stations of the Church,
have had to contend with peculiar difficulties in childhood,
arising from untoward circumstances.

By her own account,
filial affection and submission to the requisitions of her surviving parent,
were felt to be imperative duties,
as well as a strict compliance with the testimonies of the Society, in dress and address,
and the steady attendance of meetings for divine worship.
Her growth in the work of religion, was the fruit of resignation to the Spirit of Christ,
in her own heart, which often drew her into retirement;
and the qualification to preach his gospel, a gift for which work was committed to her,
is referred to the ability he gives, in the renewed openings of the same spirit.
In addition to the cloud of witnesses that have gone before,
her simple narrative exhibits some of the events in the life of another,
who through the obedience of faith exercised under many bodily infirmities,
was frequently employed in active religious duty, and became an example in word,
in conversation, in charity, in spirit, in faith, and in purity.

May the rising generation,
be incited by the dedication of the faithful servants of Christ,
to follow their footsteps, in the path of daily self-denial.
Walking in this path, conformably to the will of God inwardly revealed,
they will be redeemed from the power of their corrupt propensities,
and inherit substantial peace, which surpasses all the fleeting gratifications of time,
and is a foretaste of those joys, which are incorruptible, and undefiled.
It is this path, the holy ancients ever trod to blessedness,
in opposition to the sneers of the unbeliever, the scoffings of the hypocrite,
and the laugh of a vain and deluded world.
