== Memoirs of Elizabeth Collins

It has been repeatedly revived in my mind,
to leave some hints of the gracious dealings of the
Lord my Creator with me from my youth.
I was born the 4th of the first month, 1755, of religious parents,
Joshua and Naomi Ballinger.
My father died when I was little more than six years of age,
leaving my mother with six small children,
and not an abundance of this world`'s treasures, to bring us up with.
It was my lot to live out from home, and I had some trying seasons to pass through,
both in body and mind, but my gracious Helper was near in those my young days,
though like Samuel, I knew not who He was.
Lodging alone,
I had a full opportunity to pour out my tears and to make
my moans undiscovered but by Him who searcheth all hearts;
blessed be his name, his supporting arm was underneath.

Before I was twelve years old, my bodily weakness increased,
so that I was obliged to go home to my mother, where I lived until more than fifteen,
under the care of an affectionate parent, who watched over me for good,
and kept me steadily to religious meetings, which was of use to me,
and is the duty of all parents, and those who have the care of youth.

In the fourth month, 1770, I went an apprentice; where I was much exposed,
and met with many difficulties, but the invisible arm of divine love and mercy,
was near for my preservation; blessed be the great name of Israel`'s God,
who alone preserved me from utter ruin; in the remembrance thereof,
my soul can but bless, praise and magnify his ever worthy name.
Although I took some delight in company and light conversation,
yet I had often to retire, and pour out my tears before Him who seeth in secret,
and who had, in mercy, visited my soul,
and given me in measure to see the vanity of youthful pastimes,
that I had too much delighted in.
The time of my greatest indulgence in this way,
was before I arrived at the age of fifteen years, and through mercy I was so preserved,
that I do not remember ever to have expressed a bad word in my life,
or scarcely ever told an untruth, or said you to a single person: when I did,
I was sure to meet with the reprover.
I was mostly attentive and obedient to my dear mother, but on one occasion,
when going to attend a marriage,
I was informed she should expect me to return in the evening,
and requested me not to remain out late, to which I replied, I thought I should not;
but being over persuaded by my companions, I stayed until near midnight,
spending the time in lightness and vanity, for which I was closely reproved,
even in the midst of folly.
I verily thought I felt as if a fire was already kindled in my breast,
so great was my condemnation at that time;
and I have often admired that children could act
so contrary to the will of their tender parents.
This I think was the greatest instance of disobedience to my mother,
that I was ever guilty of.
After the expiration of my apprenticeship,
I attended meetings as steadily as my situation would admit,
being obliged to go from house to house, to work at my trade,
in the course of which I met with many trials, being much exposed to company.

About the eighteenth year of my age,
I entered into the marriage covenant with John Mason, of Evesham,
who was a truly affectionate husband to me;
few I believe ever lived together in greater harmony and love than we did.
But He who I believe brought us together, saw meet to separate us,
in a little more than four years.
A short time before he expired, in a very affectionate manner, he said to me, "`Well,
my dear, I think we have nearly fulfilled our marriage covenant,
and shall have nothing to answer for upon that account;`" the remembrance of which,
has afforded comfort and satisfaction to my mind at times ever since.
He also expressed, that he saw nothing in his way, and believed he should go to rest.

Being now left a poor disconsolate widow with two small children,
I was ready to conclude, that no one`'s trials could exceed mine; but the Lord, in mercy,
was near to support and bear up through all, that I did not sink below hope,
though often brought very low both in body and mind,
in which seasons I wrote the following.
My heart seemeth somewhat humbled within me,
and my desire is that I may be preserved as in the hollow of the Lord`'s mighty hand,
who am a poor unworthy creature; but he is wonderful in goodness; he hath spared, pitied,
and showed mercy, that I am not cast off and quite lost.
O that I may ever look to Him, who is as a strong tower to the faithful,
against the mighty; that I may ever walk worthy of the Lord`'s notice,
that he may become a father and a husband to me.
O Lord, may I enjoy thy presence, or else my time is lost, and my life a snare to my soul!

O! that my head were as waters, and mine eyes as a fountain of tears,
that I might weep day and night, until acquainted with my God.
Oh, that I may receive bread from thy table, and that thy grace may abound in me.
May we all turn to the Lord as with one heart, and he will do wonderful things for us,
if we seek him aright.
Oh that we were wise, and fervently concerned,
to seek the accomplishment of this great and necessary work in us,
that we may be found in a state of preparation for that awful moment,
when the dust shall return to the earth as it was, and the spirit unto God who gave it;
then may we hope, that when Christ, who is our life, shall appear,
we also shall appear with him in glory.

I also felt great yearnings of heart towards my fellow creatures,
and much tenderness and compassion for the brute creation,
believing they were lent to us for our use, and not for our abusing.

A short time after the death of my dear husband, I had a severe attack of disease,
in which I had no prospect of recovering, nor any desire,
but was quite resigned to the divine will;
desiring that if He saw meet to raise me again, it might be for some good end;
in the remembrance of which season, I feel breathings of soul,
that I may be so attentive to the pointings of Truth,
and so obedient to my dear Lord and Master, as to answer this great end.
Gracious and holy Father, may it please thee to strengthen my feeble endeavours,
and more and more wean me from everything that obstructs the growth of thy pure Truth.

In the year 1778, I joined in marriage covenant with Job Collins, of Evesham.
Now, settling in a new neighbourhood, I kept close to meetings, as I had done before,
and sometimes spake to business in meetings for discipline.

+++[+++In the twenty-fourth year of her age, she gave up to more public labour,
believing it required of her to appear as a minister in our religious assemblies.
Respecting the state of her mind in entering upon this new and important work, she says,
My mouth being thus opened, I was ready to conclude I should be more steadily favoured,
and not experience such deep exercise as I had passed through, but was disappointed;
for although I had great peace,
in giving up to speak a few words in meetings when required,
yet I often had to experience close baptisms; such stripping seasons,
that I have been ready to call all in question, and conclude that I have been misled,
and that it was not required of me to speak in public.
But my great and good Master, who saw my distress, suffered me not to sink,
but condescended in mercy to favour at seasons,
with the lifting up of the light of his glorious countenance,
whereby my poor drooping spirit was raised and comforted.]

My friends showed great kindness and sympathy towards me.
I was often appointed to services in the Church,
in which part of the labour in Society I have had a considerable share,
sometimes in visiting families.
In the first place,
I joined a committee of our monthly meeting in visiting
those who stood foremost in the meeting;
afterwards, in 1784,
I joined our ancient friend Isaac Zane and others
in visiting the families of Chester meeting.
This was a time of favour to many,
and more especially to some of the inhabitants of Moorestown;
but if these seasons are not improved, they will add to our condemnation,
and if those who are called, refuse to be gathered,
they will be left and others be called in.
It was a considerable trial to me to give up to this service,
having a young child about four months old, and weakly,
but my friends`' kindness towards me was very great in taking care and making way for me.

After this I stayed much at home, and had many hard spells of sickness,
through which I was mostly preserved in patience and resignation to the divine will;
and was at times so favoured with the incomes of love and peace,
that I could say it is enough, and dare not desire my situation altered.
I steadily attended meetings when of ability,
and cannot find any thing short of sickness,
or the care of young children a sufficient excuse to stay from them.
I was sometimes admitted to the divine fountain therein,
but often had to sit as with my mouth sealed or in the dust,
under a deep exercise and inward travail of spirit.
This has been increased on my part, for want of more faithfulness;
for often when things have been presented to my mind to offer,
I have given way to reasoning and a fear of being deceived,
or getting before my true guide, so that I have lingered too much behind;
and thereby brought great darkness, poverty, and distress over my mind.
But my great and good Master, who knew my heart,
and that it was not stubbornness or wilful disobedience, but a fear of missing my way,
in mercy looked upon my weakness, and again admitted me into favour with him.
I may here note, that sitting in a meeting at home under exercise,
a few words presented to express, but for want of attending singly to the opening,
I gave way to reasoning and putting off, which has too often been the case,
until the meeting was nearly over;
when this language was intelligibly spoken to my inward ear,
if thou art not more faithful, thy gift shall be taken from thee.
The language was awful;
I was brought to see the deplorable situation I should be left in,
if after receiving so precious a gift, I should neglect to improve it,
and it should be taken away, and I left poor and distressed.
I was led to cry for mercy and for strength to be more faithful;
and in fear and trembling, I arose and expressed what was before me.

I had many deep and close exercises to pass through,
which nothing short of the divine arm of Omnipotence, could have supported through;
about which time I wrote as follows:

Unto thee, O thou Searcher of hearts, I commit myself, O Lord search me, and try me;
if there be iniquity in me, do thou it away.
Let not thy blessed hand spare,
nor thy holy eye pity until thou hast brought judgment into
victory--until thou hast made of me what thou pleasest,
for thou knowest for what cause I am thus tried.
O Lord be pleased to visit my dear children, now in their young and tender years;
turn their hearts unto thee, and one unto another.

Be graciously pleased to enable me to keep my place and authority over them, in thy truth.
Create in me a clean heart,
and renew a right spirit within me--a right disposition of mind,
to bear all things that may fall to my lot, for the trial of my faith and love unto thee,
O thou beloved of my soul.

In the third month, 1790,
I visited the families of Friends and others who make profession with us in the
neighbourhood of Mullicahill--attended the select preparative and the monthly
meetings of Haddonfield and Woodbury--was at the week-day meeting of Upper Greenwich,
and that on first-day at Pilesgrove.
We were favoured to get through our visit, and returned home in less than two weeks,
having experienced holy help and divine counsel to be near,
and believe it was a fresh visitation to many.
It was no small trial to leave home at this time, having several small children,
but was favoured to get where I could leave them to the care of Him,
who is the great caretaker of his people.
In the winter following,
I joined a friend from Pennsylvania in visiting the families of Friends and many others,
belonging to Evesham, and of those of the upper meeting.
This visit was attended with difficulty and deep exercises, both of body and mind,
but I was favoured to get through to satisfaction.

Soon after, I was taken with a hard spell of sickness, wherein I was brought very low,
and had no prospect of getting well, but was much resigned to Him,
whose right it was to dispose of me as he saw best,
who was pleased to continue me here sometime longer.
O may I be industrious to improve the few days allotted me,
as also those talents committed to me for improvement.

In the fifth month, 1791,
I joined several friends in visiting the families
of Cape May and Great Egg-Harbour monthly meetings,
which we were favoured to perform to the peace and satisfaction of our own minds;
then attended our quarterly meeting at Salem; returned home and found all well.
I may here note that before I left home, being under a deep exercise of mind,
having another little journey in prospect,
I was desirous of putting this off some time longer,
when this language was intelligibly communicated to my mind; thy day is but short,
thou hadst need to be industrious.
This intimation, I think, has been of use to me, as it has often revived,
and at times raised a desire, that I might press through all,
and endeavour to do my day`'s work in the day time;
that I might be favoured in the evening, the end and conclusion, with the answer of,
Well done, good and faithful servant, enter thou into the joy of thy Lord,
which is far more desirable than the increase of outward treasure.

In the tenth month, I set out with the unity of my friends,
in company with W. Rogers and Rebecca Cowperthwait,
to visit the meetings that constitute Shrewsbury and Rahway monthly meetings.
We attended the general or yearly meeting,
which began on seventh-day with a meeting of ministers and elders,
and concluded on third-day.
It was thought this was a solid meeting.
We then proceeded to Squan, Squancum, Rahway and Plainfield.
After the latter, we attempted to return homeward, but not feeling easy to proceed,
turned back and went up the mountain to a little meeting called Mendham,
which proved a memorable one,
and concluded in humble thanksgiving and praise unto Israel`'s Shepherd,
who is worthy forever.
Returned home with a peaceful mind.
It was through great difficulty I left it, under many discouragements;
in part from a sense of my own unworthiness, and inability to do any good thing,
and a fear of missing my way, and so bringing dishonour upon the blessed Truth,
which I have at times felt nearer to me than my natural life.
This language was mercifully revived, which greatly strengthened my poor drooping mind,
"`a little one shall become a thousand, and a small one a strong nation.`"

In the ninth month, 1793, I attended the yearly meeting in the time of the sickness,
called the yellow fever.
I left home to be at our select and quarterly meetings, with an humbled mind,
having a prospect of proceeding to the yearly meeting.
The select meeting was in measure owned by the Great Master, and was a solid time,
more especially in the appointment of representatives:
those who felt their minds engaged to attend, were desired to give up their names,
which number was small; the quarterly meeting held next day, was also a solid meeting,
no other Friends being appointed representative, but those named at the preceding.
On seventh-day crossed the river, and attended the select yearly meeting,
which was a good one,
our hearts being bowed in thankfulness to the Father of all our mercies.
First-day attended Newtown meeting to good satisfaction.
Hearing some very discouraging accounts, I felt great weakness and stripping, yea,
leanness of spirit, and my faith seemed taken from me.
Before I left home, my great and good Master had condescended to inform me,
that if I would go and keep my place, my life should be given me for a prey,
and that according to my faith, so should it be unto me.
I spent the night without sleep till near day, when my faith again revived,
and I got some sleep--awoke with thankfulness of heart to the great Author of all good.

Second-day morning, crossed the river with bowedness of spirit,
and attended the forenoon meeting, which was a solid time.
The representatives being called, but few answered to their names; from three Quarters,
not one.
In the afternoon the epistles were read, and an appointment made to answer them,
of which number I was one; this brought great weight and exercise over my mind.
Third-day morning at eight o`'clock, went to select meeting, which proved a solid season,
wherein our hearts were bowed in humble thankfulness before the Lord,
for his abundant mercies bestowed upon us.
At three in the afternoon, Friends met, and some of the epistles were read,
and with a little correction approved; this was a comfortable meeting,
several living testimonies being borne, to the humbling of our hearts together,
into contrition and holy fear.
Fourth-day morning Friends met, and the other epistles were read and approved,
also some memorials of deceased Friends, tending to incite to faithfulness,
which caused me to look over and consider my past life,
and see wherein I could have done much better.
May I be incited to improve thereby!
In the afternoon was the parting meeting; a highly favoured season, but little business;
we were favoured to part in that near fellowship that is not to be expressed.
O may we be thankful therefore, to the great Author of of all good.

This is a solemn time in this city,
wherein many houses great and fair are left without inhabitants,
many faces gather paleness, and many hearts are filled with sadness.
Many I believe, as was formerly recommended,
are getting as between the porch and the altar, crying, "`Spare thy people, O Lord,
and give not thine heritage to reproach.`"
I have entered this city and remained in it without fear, except the fear of the Lord,
which at times fills the hearts of his humble dependent children.
May I be truly thankful for this and every other mercy!
Next day attended Haddonfield meeting, which was comfortable,
and the day following returned home under an humbling sense of divine regard,
having to remember those expressions of Jacob, "`With my staff I passed over this Jordan;
and now I am become two bands.`"
I had nothing but the staff of faith to lean upon, and now in my return,
I have to experience a good degree of holy quiet and the incomes of sweet peace,
which is more to the immortal soul, than all that this world can afford.
O may it be more and more prized, and sought after by me, is the desire of my heart.
In looking over the above remarks, my soul, doth bless, praise,
and magnify that holy hand and arm,
which preserved his children unhurt even in the flames,
whose power is the same yesterday, today, and forever.

After this I was much confined at home, with the care of young children,
one of whom was very weakly.
One day as I was nursing, feeling my mind more than commonly calm and quiet,
and desirous that I might do my duty faithfully, and be resigned to the divine will,
this language was intelligibly spoken to my understanding,
"`there will be a great sacrifice required of thee.`"
This intimation, I have thought, was a singular favour from divine kindness,
in preparing my mind to meet those trials I had to pass through,
in about two months after, in burying three of my children.
I may with gratitude observe, that as I was sitting by the second that departed,
and saw her breathe her last, which proved a trial to me,
as we had buried one the day before, this language was uttered in my inward ear,
"`Just entering that city whose walls are salvation,
and her gates praise.`"--This so quieted my mind, that I could say, "`it is enough,
it is enough, thy will, O Father, be done.`"
The other weakly child continued three weeks and one day after,
when she quietly departed like one falling into a sweet sleep.

In the second month, 1796,
I acquainted my friends with a concern that had rested on my mind,
to visit the families of such as had been disowned from amongst us,
with which they united, and Martha Allinson joined me therein.
We were accompanied by two men Friends,
and were much united in the bond of gospel fellowship.
We visited about eighty families of this description;
in some we were much favoured with the overshadowing of divine regard,
wherein counsel was freely administered, to the humbling of our hearts together.
It was through great weakness of body, and oft-times discouragement of mind,
that I performed this visit, but was enabled to get through to satisfaction,
and believe it was a visitation of divine love to many.

In the seventh month, going to a week-day meeting, under an unusual exercise,
it proved a memorable meeting to me, wherein my mind was greatly humbled,
under a sense of the goodness of the Lord towards me from my youth.
It then presented to my mind,
that it would be best for me to leave some remarks of the Lord`'s dealings with me,
for the instruction of my dear children;
and many things presented that had not been remembered for some years.
That night, as I lay in bed meditating on the goodness of the Lord to my soul,
the message that the prophet delivered to king Hezekiah was revived;
"`Set thine house in order; for thou shalt die, and not live.`"
This language was awful, yet it did not terrify me,
though I much expected it was in order to prepare for my final change.

I have been much reduced, and centered in nothingness of self,
a suitable situation to receive the wine of the kingdom; and through mercy,
I have had to partake of the incomes of holy good, in a larger degree than ever before,
for so long together,
and have been ready to conclude that perhaps my warfare is nearly accomplished;
but whether or not, my greatest desire is, that I may be fully given up.
The world and the things of it, have been sunk into such nothingness,
that I have not a name importing little enough to call them by,
comparable to the joys of eternity, that I have had a prospect of.
Center then O my soul, more and more, within the enclosure of the walls of its salvation.

Copy of a Letter to a Friend, dated Ninth month, 1796.

Dear Friend,--So I can in truth address thee,
for such has been the feeling of my mind towards thee of late; yea,
great has been my desire, that thou may not be found wanting,
when weighed in the balance of divine justice,
a season we must all meet with--wanting in any part
of thy duty to God thy Creator--wanting in love,
faith and obedience, or in example in attending religious meetings.
This, my friend, I may acknowledge, is the point I am the most concerned about,
as it is our reasonable duty to assemble together, in order to worship our great Creator,
and what the apostle earnestly recommends, I think in these words;
"`I beseech you brethren, by the mercies of God,
that ye present your bodies a living sacrifice, holy, acceptable unto God,
which is your reasonable service:`" and in another place he exhorts them,
not to forsake the assembling of themselves together, as the manner of some is;
that we find there were some in that day in the neglect of their duty.
I can truly say, it has been a comfort to me, when I have seen thee at our meetings,
and do wish to encourage thee in thy duty; and oft-times when thinking of thee,
the language of Martha to her sister Mary, has presented to my mind,
with a little variation.
Hers was, the Master is come and calleth for thee; mine to thee is, come,
for the Master calleth for thee.
Come, attend religious meetings; give up thy whole heart to serve so good a master,
as the Lord of life and glory,
who is a rich rewarder of all them that give up in faithfulness and true obedience.
This is the language of Truth.
But the enemy of all good, will endeavour to keep us back,
by persuading us that there is no need of so much circumspection
and care--that we can be as good at home;
and others who attend meetings, miss it in this and the other thing;
and so discover to us the mote that is in our brother`'s eye,
and doth not let us see the beam that is in our own, our misses and neglects.
Perhaps this has been the reasoning of thy mind at seasons.

If so, dear friend, my desire is that thou may no longer reason with flesh and blood,
but give up to the heavenly vision.
Give up in faithfulness to the pointings of truth in thy own heart;
follow thou in true obedience the Captain of thy soul`'s salvation,
who will lead thee in the way of safety,
and in the end give thee an admittance into the mansions of rest and peace,
which are prepared for the righteous only:
that this may be thy happy experience is what my spirit breathes for.

From thy well wishing friend,

Elizabeth Collins.

In the ninth month, I attended our select and quarterly meetings,
which in the main were solid,
although some deep and painful exercises were passed through.
Then attended the yearly meeting at Philadelphia, which was large;
wherein many weighty matters were feelingly and pertinently spoken to,
and nothing more fully than that of love and unity, the badge of true discipleship;
the want of which, I believe, is a great loss and hurt to many.
This subject brought great weight and exercise over the meeting,
and over me as an individual.
Great was my desire for Friends in general, and more for our particular meeting,
but especially my dear offspring,
that they might be more and more partakers of that love and unity,
that becomes and distinguishes Christ`'s followers;
that they may not only be his by creation, but by redemption also: for God is love,
and they that dwell in him, dwell in love.
Many other matters claimed the care of Society;
as that of the superfluity of the hair and head dress,
and the unnecessary long trails to their gowns, that many of the youth wore.
But we were favoured with the company of many amongst the youth whom the Lord had visited;
has prepared and is preparing for his work and service,
who afford a comfortable prospect of a succession in the Church.
I was favoured to attend all the sittings of this meeting but the last,
of which I was prevented, by returning home before it was over.
This I have thought was a loss,
and wish to encourage all that give up to attend those large and solemn meetings,
as we know not which one may be the best, to stay them out;
for oft-times the best wine is kept until the last, and as Friends keep in the patience,
they are made partakers of that, which enables them to gather up the fragments,
and carry home that which will prove as bread to them to live upon many days.

Tenth month.
Thou, most holy and righteous Lord,
art more and more weaning me from the pleasant things of this world;
perfect thy work to thine own praise.
Let not thy hand spare nor thine eye pity,
until thou hast perfected thy intended purpose;
until thou hast made of me what thou pleasest.
Thou only knowest what food is most convenient for me.
Be pleased, in mercy, to mete out the dispensations of thy providence,
in a way and manner that may tend to the firm establishment of my faith in thee,
O thou immovable Rock.

In looking over my life, even from the days of my youth,
I have to admire the many preservations, gracious dealings, tender mercies,
and loving kindnesses of the Lord, my bountiful Creator, towards me,
a poor unworthy creature.
My soul doth bless, praise, and magnify his great and ever worthy name,
and can with some degree of propriety adopt the language of Jacob,
when he blessed Joseph and said; "`God,
before whom my fathers Abraham and Isaac did walk,
the God which fed me all my life long unto this day,
the angel which redeemed me from all evil, bless the lads;
and let my name be named on them, and the name of my fathers Abraham and Isaac.`"

But we cannot suppose, that to be called the children of Abraham,
or of believing parents, will do any thing for us.
We may remember that our dear Lord and Saviour told some in that day,
that to be the children of Abraham, was to do the works of Abraham;
that it is not a name, or a profession, but a possession of the Truth, that will do.

Oh! may the Lord, in mercy, so visit and so open the understandings of my dear children,
as not only to see the beauty of the Truth, but to join in with,
and receive it in the love of it.
So wisheth, and so prayeth, your truly exercised and deeply concerned mother.

A singular instance of the love and mercy of Almighty God, as also of his just judgment,
in the case of a young man, happened in my early life.
He lived at a public house, and was one who took great delight in company,
vanity and horse racing.
One day, as he and one of his companions were running horses,
at the end of the race ground he was dashed with great violence against a tree,
the horse taking the opposite side from that he expected to go,
which brought his head directly against the tree.
He was taken up, and carried into a house for dead.
A doctor was sent for, who gave no encouragement of his recovery;
but after a time he revived and in a few days recovered his understanding.
Oh! the distress and anguish he was then in, having no other prospect,
but shortly to be summoned before an offended God, to receive the sentence,
"`depart from me thou worker of iniquity.`"
Bitter were his moans, sore his lamentations, and fervent his cries for mercy.
I went to see him in his distress, when it was not in the power of man to relieve him.
His petitions were for mercy and for time;
he asked only for one year that he might live a new life,
be an example and warning to his companions, and honour and glorify God his Creator.
The Lord in mercy heard his petition, and in great condescension granted his request,
even to a miracle, as it was thought impossible for him to be raised,
and gave him not only one year, but several.
For a time he lived a sober, watchful, and orderly life,
but for want of breaking off from his old companions, and living a more retired life,
he at length, fell by little and little, away,
and got into the same paths of folly and dissipation.
He was not, however, suffered to go on long in this way,
for one evening as he was riding with several of his companions,
one of whom he expected to be joined to in marriage in a few days,
his horse without any fright that they could discover, ran off,
threw him in the road and killed him.
I was told he never drew breath after they reached him, that they could discover.
This event happened in the evening,
after spending the first-day afternoon in lightness and vanity.

Oh! may the rising youth, and all others, be warned to beware of spending the first-day,
in an unprofitable and light manner, and also of breaking their covenants,
which they have made with God Almighty.
As this solemn instance of divine mercy and justice,
has from time to time been revived in my remembrance,
I have thought it best to commit it to writing,
as a caution and warning to my dear children,
to beware of loose and unprofitable company, and of breaking their covenants;
for the Lord our God is a covenant keeping God;
he keepeth covenant and showeth mercy unto thousands
of them that love him and keep his commandments:
but he is not to be trifled with.
He is just and equal in all his dealings with the children of men.
Oh! may I not say, and that from living experience,
that great and marvellous are thy works.
Lord God Almighty, just and true are all thy ways, thou King of saints.

In the third month, 1797, I attended Newtown meeting on a first-day,
which was a deeply exercising season in the forepart, but after deep wading,
truth arose and the meeting ended to satisfaction.
Second-day, attended Haddonfield select and monthly meetings,
which were solid and instructive; then returned home with peace of mind.
I also attended our select and quarterly meetings,
which were favoured with the divine presence, and the spring meeting at Philadelphia,
which was a solid and deeply instructive season,
wherein many close and weighty remarks were made,
tending to stir up to more faithfulness,
and inward attention to the great Lord and Lawgiver.
On my way home next day, stopped at Moorestown meeting, which was a quiet sitting,
and in the evening reached my habitation and found all well.
May living praise and thanksgiving be rendered to the great Shepherd of Israel,
who maketh way for his depending children, even where there seemeth to be none.

I was prevented this season from attending the yearly meeting at Philadelphia,
which was a solemn time, the city being again visited with the yellow fever,
which removed many from works to rewards.
Thus the Almighty is visiting and revisiting, both in mercy and in judgment,
and from time to time threatening and shaking his rod over our land,
in order to humble and bring us to a sense of our duty to Him,
the great Giver of all good.

Feeling the revival of a concern that had for a considerable time rested with me,
to visit Friends at Maurice River, the Egg Harbours, along the shore to Shrewsbury,
and the upper part of New Jersey,
I laid the same before Friends in our monthly meeting in the third month, 1798,
and obtained their unity and certificate.
I left home the 8th of the fourth month, and after attending our first-day meeting,
which was a favoured season, parted with my Friends and family in much affection.
We set out next morning for Maurice River, and had meetings there, at Dividing Creek,
Cape May, Mays Landing, Great Egg Harbour, two among people of other societies,
one at Batsto, at Bass River, and Barnegat;
in these meetings ability was given to labour,
and Truth arose into dominion in a good degree; blessed be the name of the Lord forever.
Reached Squancum much fatigued, having rode forty miles and attended a meeting.
We were at the meeting here, which was small and laborious, also Squan and Shrewsbury;
in the latter, Truth at length arose and ability was given to labour,
wherein the honest-hearted were comforted, the lukewarm aroused,
and the dear youth cautioned and warned to flee from the evil of their ways, +++[+++such as]
bad company, sabbath-breaking, etc.,
and invited to come and enlist under Christ the captain of their soul`'s salvation.
I had great peace, and was thankful in heart,
that ability was given to labour to the relief of my mind:
blessed be the great Helper of his people.
Next day rode thirty-five miles to a Friend`'s house,
to whom I mentioned a concern that had rested with me,
to have a meeting in the town of Brunswick, a place where no Friends lived.
This was a trying season, deeply so; but Friends were very kind,
and obtained liberty for a meeting in the courthouse, to begin at the third hour,
to which many of the inhabitants came, a Presbyterian priest,
several doctors and lawyers, who mostly behaved well.
The under sheriff took some pains to place the children,
and charged them to keep their seats;
and I may with thankfulness acknowledge that He who engaged my heart to visit them,
did not leave me when there,
but gave strength to labour to the peace and satisfaction of my own mind;
blessed be his great name forever.

Next day attended Plainfield meeting; and on fifth-day was at Rahway,
a favoured season wherein Truth reigned.
Rode up to Mendham and attended the meeting, wherein I think it may be said,
Truth reigned over all--thence to Hardwick; the road being rough and steep,
we could not reach our lodgings till dark,
and drove against a rock that overturned our carriage,
but through mercy we were not badly hurt--we were at that meeting,
which was large and exercising, but at length Truth rose into dominion in a good degree.
Next day had a meeting at Sussex courthouse, to which many of the inhabitants came,
also a few Friends; wherein some relief was afforded.
We rode up Scots mountain the following day,
and had a meeting at the house of Ephraim Parker, to satisfaction.
I may here note the great care and attention of the Friend,
in preparing seats and giving notice to his neighbours, the like I had not seen.
He had lately built a large stone house, and made it convenient for the purpose,
by hanging shutters, that the front could be thrown open forty feet in length.
Our next meeting was at Kingwood, which was a very trying time, and but little relief;
appointed a meeting the succeeding day, it was large,
and ability was afforded to labour to the peace of my mind.
Then rode to Stonybrook; during the ride my mind was much humbled,
with a prospect that had presented some days before,
of having a meeting with the inhabitants of Princeton.
Under this concern,
I found it hard work to come to that resignation of mind wherein I could say in truth,
"`Thy will, not mine, be done.`"
First-day attended Stonybrook meeting, wherein Truth reigned in a good degree;
and in the afternoon, one at a Friend`'s house for the inhabitants of Princeton,
which was favoured with the ownings of Truth,
and ability was given me to labour amongst them.
Lord, make of me what thou pleasest;
work in me to will and to do of thy good will and pleasure;
bring my will more and more into subjection unto thy most holy will,
whose right it is to dispose of thy people as thou seest meet.
Our next meetings were at Trenton, Bordentown, Mansfield, and Mansfield-neck,
some of which were painful and laborious, others more open.
From thence to Crosswicks, Robinson`'s meeting, Upper Freehold, Mount, and Mount Holly,
Upper and Old Springfield, Rancocas and Burlington; some of them favoured seasons,
wherein Truth rose into dominion.
Returned to Mount Holly and held a meeting there in the forenoon,
and in the afternoon at Vincentown, the former a close searching season,
wherein I was favoured to obtain relief; the other small, but satisfactory.
I reached home that evening,
thankful in heart to the Great Helper of his people for his many mercies received;
having rode in this journey about seven hundred miles, attended forty-four meetings,
and was absent nearly seven weeks.

After my return, I had many deep exercises and close trials to pass through,
insomuch that at seasons, I was ready to fear I should not keep my place,
and oftentimes fervent desires were raised,
that all these afflictions might be sanctified to me,
and have the happy effect to centre deeper and deeper in the root of true religion.

In the eleventh month, 1798, I obtained a minute of concurrence from our monthly meeting,
to visit the meetings within the limits of Salem quarter.
Our first meeting was near Chew`'s Landing; the weather being inclement, it was small,
but favoured with the overshadowing wing of Divine regard;
and those met sat very becoming the solemnity of the occasion.
Next day at Upper Greenwich in the morning, wherein holy help was near,
and ability given to labour in a close line; in the afternoon at Mullicahill,
next day attended Pilesgrove monthly meeting, sixth-day at Penns neck,
on first-day an appointed meeting at the head of Alloway`'s Creek,
and second-day their monthly meeting at Salem, which was comfortable;
there appears to be some hopeful Friends, especially among the younger class,
who were encouraged to faithfulness.
Third-day at Greenwich, fourth-day at Alloway`'s Creek monthly meeting,
a favoured season; under a sense whereof I had renewedly to acknowledge; Thou Lord,
art strength in our weakness, mouth and wisdom,
yea all things to thy humble dependent children, whose trust is in thee,
waiting for thy putting forth in the way, and gently going before them;
blessed be thy holy name forever!
Next day at Pilesgrove to satisfaction; on sixth-day at Woodbury,
an exercising time in the forepart, but through close attention,
Truth rose into dominion in a good degree.
Returned that evening to Joshua Lippincott`'s,
thankful in heart to the Great Helper of his people,
who had been near and supported through many close exercises,
and in much weakness of body,
that at times it looked unlikely I should be able to get through;
but as mine eye was kept single to my Holy Helper,
I had to acknowledge with the disciples, I lacked nothing.
Before I sat out on this little journey,
I had many difficulties and discouragements to pass through,
which oftentimes looked insurmountable,
like mountains and floods that could not be passed over.
But as my mind became truly given up to Him,
whose right it is to dispose of us as he sees meet, how were those difficulties removed,
that I could even adopt the language of the Psalmist: "`What ailed thee, O thou sea,
that thou fleddest?
thou Jordan that thou wast driven back?
ye mountains that ye skipped like rams, and ye little hills like lambs?`"
Thus I had from time to time to set up my Ebenezer and acknowledge,
"`hitherto thou hast helped me.`"
Attended our select meeting on seventh-day,
returned home and found my family in good health.
Second-day was our first quarterly meeting at Evesham; a very large and solemn meeting.

Twelfth month attended the yearly meeting at Philadelphia,
which had been adjourned in the ninth month on account of the fever,
with which the city was again visited.--The meeting
was favoured with the ownings of Truth.

In the ninth month 1799, I obtained a certificate of unity from my monthly meeting,
in order to fulfill a prospect that had attended my mind for a considerable time,
to visit Friends at the settlement of Redstone.
Left home 7th of the tenth month, under great bowedness of soul,
lodged at my brother John Collins`', and next day attended Chester preparative meeting,
wherein my gracious Helper was pleased to favour with a
comfortable evidence that my going forth was in his counsel,
and by his holy approbation.
Crossed the Delaware that afternoon, lodged near Frankford,
and next morning pursued our journey,
in company with some Friends who were going to attend the yearly meeting at Baltimore.
We reached the city on seventh-day morning before meeting time,
and attended all the sittings of the yearly meeting, which concluded on sixth-day,
and was considered a solid good meeting.
After dinner we set forward towards Redstone,
in company with some of the Friends of that place;
attended the first-day meeting at Newmarket, which was favoured with the presence of Him,
who is all in all.
On third-day evening, we put up at Clayton`'s tavern,
where we had a solid opportunity in the family,
with a large number of persons removing and many other lodgers;
this opportunity was very unexpected, and tended to strengthen my drooping mind.
In riding these difficult roads, and crossing the rivers and mountains,
we had humbly to admire the works of an Almighty Creator.
Sixth-day we reached a Friend`'s house where we lodged,
and on first-day attended the meeting at Sandy hill, which was a solid favoured time;
that night reached our valued friend Jonas Cattel`'s,
and next day accompanied my brother Moore to his house, to see my dear sister.
Our joy was mutual, and I thought resembled that of Joseph and his brethren,
having been separated several years, and not expecting ever to meet again.
Here I rested some days, attended the preparative meetings of Redstone and Providence,
both favoured seasons.
On sixth-day, the 1st of the eleventh month,
I laid my concern before the monthly meeting of Redstone,
to visit the families of that particular meeting, with which Friends united,
our friend Jonas Cattel joining us therein.
We visited all the families belonging to it.
Their remoteness from each other, and the roads hilly and rough,
with the lukewarmness of many, made it truly a laborious exercise;
but best help was near, and mercifully favoured us from house to house,
and being strangers to their situations, we could speak plainly to them as things opened,
and believe it was a fresh visitation to many.

Having visited the families, and all the meetings hereaway, and being desirous to return,
as soon as we might be clear to leave the place,
we proceeded about ten miles towards home, attended Sandy hill meeting,
but our way not opening to proceed, we returned to Jonas Cattel`'s,
and attended the select meeting at Westland, their monthly meeting,
their first-day meeting, and one appointed at Fredericktown, both favoured meetings.
Third-day we were at the select meeting of Redstone,
fourth-day their preparative meeting, that of Providence on fifth,
sixth their monthly meeting, which was a low time,
and seventh-day the select quarterly meeting of Redstone, in a school house.--Next day,
1st of the twelfth month, attended the first meeting at the new meetinghouse,
which was large, and favoured; second-day, the quarterly meeting,
which was also large and in the main well conducted, ending with a good savour,
after a solemn time in supplication,
and humble thanksgiving to the Father and Fountain of all sure mercies,
who is worthy forever.
Feeling easy to leave the neighbourhood of Redstone, we proceeded towards Sandy hill,
and entered on a family visit to the members,
it being a branch of Redstone preparative meeting: and on the 8th of the twelfth month,
having nearly finished the visit in this neighbourhood,
we held a public meeting at Beesontown, in the courthouse,
to which many of the inhabitants came: it proved a highly favoured season,
wherein the gospel flowed freely,
towards a large gathering of people of different denominations as to religion;
may the praise be rendered unto him, who remains to be the alone Helper of his people,
and is worthy of all praise forever.--In a few days we completed the visit here,
having attended their meeting divers times in course,
wherein ability was given to clear myself amongst them, so that I left them in peace,
and went to Sandy creek.
Visited the few families there, and attended their first-day meeting,
the last over the mountains, which through adorable mercy proved a favoured season.
On the following day, the 16th, sat out to cross the mountains,
and reached the settlement of Friends in Virginia, in about five days.
Our home was principally at Abel Walker`'s,
and we attended all their meetings in that part, also the preparative at Crooked run,
the monthly meetings at Center and Hopewell, sixteen in all,
many of them mercifully favoured with the overshadowing wing of divine love and regard,
wherein strength was given to labour in a close, yet feeling manner,
as also in most of them at Redstone, to my humbling admiration.
One instance I may here note of a meeting at Redstone,
appointed for the inhabitants of Brownsville,
a little village that has no settled place of worship in it.
The meeting was held on first-day afternoon, and as we were riding to it,
we observed a collection of people at the river side, which we were afterwards informed,
was occasioned by a baptist minister,
who had come many miles that day to officiate among them,
and was there baptising some of them.
After they had finished, he and most of the people, came to our meeting;
it was a large gathering, which the house could not near hold,
and was eminently favoured,
ending very solemnly in humble thanksgiving and praise to the Lord Most High,
who is worthy forever.
After meeting, we parted with this Baptist,
in a degree of that love that unites the children of the Heavenly Father`'s family,
though of different denominations as to religion; under a grateful sense whereof,
my soul was led humbly to worship and adore Him who lives forever and ever.

After Hopewell monthly meeting, we proceeded homeward, attended Berkley monthly meeting,
the last we were at in Virginia, crossed the Potomac,
and reached little York meeting on first-day, from thence to our respective residences;
my companions arriving at theirs on fourth-day evening, and next day I got to mine,
where I found things better than I expected,
my family having met with some close trials by accidents, but were much recovered.
I was truly glad to get home,
where everything looked pleasant and everything spake peace,
as to the state of my own mind; after being absent three months and nine days,
having been mercifully favoured with the presence of Him,
who putteth forth his own and goeth before them; yea, maketh way for them,
where there seemeth to be no way, and is mouth and wisdom, tongue and utterance,
all in all to his truly dependent children.
Under a grateful remembrance of thy saving help,
that has been mercifully vouchsafed from season to season, my soul doth bless, praise,
and magnify thy most adorable name, who art God over all blessed forever!

1802+++.+++ I have been but little from home for several years,
except at our quarterly and yearly meetings as they came in course,
and have experienced them to be seasons of deep instruction.
May we in this highly favoured land, prize our privileges.
Also at times, as way opened, I have attended neighbouring meetings,
and have been favoured mostly to keep my place in them, though sometimes,
I have given way to a diffident reasoning disposition,
a fear of getting or going before the true Guide, and have too much lingered behind,
and neglected doing what has been assigned for me to do,
and thereby brought poverty and weakness, and increased my affliction.
But He who knows how to deal with his children,
and knows that it has not been through wilful disobedience,
but rather a timid disposition, when he has seen my affliction was enough,
has been pleased in mercy, again to entrust with his precious gift,
and to enable to discharge the trust reposed in me,
to the peace and comfort of my own mind.

In this year, I accompanied Ann Willits from Egg harbour,
in a visit to most of the members, within the compass of our own meeting,
in their families.
Many were the difficulties, and varied the trials and baptisms,
through which my poor soul had to pass, best known to Him who searcheth all hearts,
yet had the reward of peace, for giving up to do the little I was capable of.
Oh! may the labour of the labourers be blessed.

In the eleventh month 1803, I joined our valuable friend Richard Dell,
from Mendham in East Jersey, in a visit to the families of Friends,
and others who attend meetings, within the compass of our monthly meeting;
and although the work was weighty and laborious, yet strength sufficient to the day,
was mercifully vouchsafed, to our humbling admiration.
In some of our sittings, particularly with those who were not members,
the hand of help was afforded, and the invitation given,
to come and enlist under the Captain of their soul`'s salvation,
and thereby experience his banner over them, to be love.
Many were the precious opportunities we had in this visit, both with members and others;
may they be closed in with.
We had about one hundred and forty-five sittings; in most if not all,
the evidence of divine kindness attended,
which is cause of thankfulness of heart to the Author of all our blessings,
who is worthy of the tribute of praise forever.

Dear Richard, in like manner, visited the families of Evesham,
and Chester monthly meetings;
it was about this time the latter was established a monthly meeting.
He was seventy-seven years of age, whilst engaged in this visit,
and was favoured to return with the answer of peace for his dedication.
I heard a friend of his meeting remark, that after he returned,
he appeared very pleasant and cheerful, as having paid a debt due from him,
being more lively, as though his age was renewed.
A great favour to be preserved green and alive in the Truth,
bringing forth fruit in old age!
He lived but a few months after his return.

Having for some time felt an engagement of mind,
to visit the families of Bristol preparative meeting in Pennsylvania,
Martha Allinson of Burlington joining me therein; we attended Middletown monthly meeting,
of which it is a branch, on the 10th of the tenth month, 1805,
where we produced our minutes expressive of the unity
of our Friends in this weighty work.
Friends uniting, we entered next day upon the service,
an elder of that meeting accompanying us therein, and visited all the families,
also others who attended the meetings.
Many of the sittings were graciously owned, by the overshadowing wing of Heavenly regard,
wherein counsel was freely communicated,
I trust to the encouragement of the humble in heart.
Some of those, not members, had never received such a visit before,
but were glad of the opportunity, and we were made to rejoice together;
we also visited their school, and attended meetings as they came in course;
finished our service on first-day morning, having a comfortable meeting at parting,
which many of the town`'s people attended.
It was large.
Truth rose into dominion, and we separated in near unity,
under a precious sense of divine regard.
O may the tribute of worship, adoration and praise,
be given to Him who still regards the dust of Zion, and satisfies her poor with bread.
After dinner crossed the river to Burlington, attended their afternoon meeting,
a quiet comfortable season.
I spent two days in and about the town, making divers visits to satisfaction,
and on fourth-day was at our own meeting,
from which I went home with the answer of peace;
having to rejoice that I had been enabled to discharge the little required of me,
I trust in faithfulness, and with cheerfulness.

It is through tribulation the righteous enter the kingdom.
O may I be willing to endure trials and tribulations, baptisms and sufferings,
and whatever the dear Master may see meet I should pass through for his sake,
who trod the same path of suffering.
He declared that the disciple is not above his Master, nor the servant above his Lord:
if it was his lot to suffer, what can we poor unworthy mortals expect?
O gracious Goodness, reduce me more and more into a state of passiveness,
willing to be abased or to abound, willing to suffer or to reign with thee,
that thy blessed will may be done in me, and through me, who am a poor worm.

Feeling the revival of a concern that had rested upon my mind,
to pay a religious visit to Friends of New York and Long Island,
I laid the same before our monthly meeting in the ninth month, 1807,
desiring its sympathy, concurrence, and certificate, which was granted,
and for many days my mind enjoyed a precious calm and sweetness.
I left home on the 16th of the tenth month, under an humbling sense of my own weakness,
and inability for the work, and also a renewed evidence of divine love and regard.
We rode to Burlington, my brother John Collins being our companion;
and Martha Allinson having obtained a certificate in order to join in the visit.
Many Friends came to see and take leave of us,
with whom we had a comfortable opportunity,
greatly to the strengthening of my poor exercised mind.
After dinner we rode to Stonybrook, and lodged at Benjamin Clark`'s;
next day reached Plainfield, and attended their first-day meeting,
wherein renewed ability was given to labour to the peace of my mind.
On second-day, landed in New York, though it was with difficulty we got across the river,
the wind being high and squally, and our horses and wagon in the same boat.
Through favour we got safe over, lodged there,
then crossed the East river to Long Island, to attend the quarterly meeting,
which began next day, and ended with a meeting of ministers and elders,
at the close of the public meeting on sixth-day: a favoured season,
wherein the Ancient of days was pleased to be near, and furnish with ability to labour,
and find relief.
Rode that afternoon to Westbury, and attended, the following day,
a meeting appointed for Isaac Jacobs of Pennsylvania, who was there on a religious visit.

In the afternoon, we began the weighty service of visiting the families of that meeting,
and were favoured with a truly useful companion in Gideon Seaman,
who offered to join in the visit; and above all, the presence of the blessed Master,
who was pleased to be near and make himself known,
as by the breaking of bread from house to house, I think remarkably so,
that in some places or families, we were all so humbled together,
I believe there was not a dry eye amongst us, neither visitors nor visited.
O may the tribute of thanksgiving and praise, be given to the Shepherd of Israel,
who is worthy forever!
We visited all the meetings upon the Island, most of them favoured,
and ability was given to labour, in a faithful discharge of duty.

Left the Island with a peaceful mind, after a solid opportunity at our lodgings,
and reached New York on sixth-day evening.
Attended the two meetings in this city on first-day;
that in the forenoon was to me a truly comfortable silent meeting,
wherein I was enabled silently to worship and adore that Almighty Being,
who had been near, helped and supported through many trials and probations,
and at times enables us to render the tribute of glory and honour,
thanksgiving and praise, unto his great name, who is worthy forever and ever.
At the afternoon meeting I was enabled to labour, and find relief,
and had a favoured opportunity in the evening at our lodgings.
On second-day morning we left New York, got into the neighbourhood of Rahway;
next day rode in company with Friends to Shrewsbury,
in order to attend their quarterly meeting,
which began with a meeting of ministers and elders; fifth-day their meeting for business;
sixth-day we had an appointed meeting, which was large,
and favoured with the ownings of Truth.
Attended Squan and Squancum, both small, the latter deeply exercising.
O the want of depth and weight amongst the professors of Christianity!
What will a name do for any, a name to live, and yet dead,
as to the life and savour of true religion?
On second-day we rode many miles through the barrens to Barnegat,
and had a small but comfortable meeting, wherein Truth gained the victory,
and we were made to rejoice together.
That evening we rode through a storm to Clamtown,
and had a large and comfortable meeting there next day,
in which Truth rose into dominion, and many were comforted.
The day following, we had a meeting at Bass river, small and deeply exercising,
but obtained some relief.
Rode round the head of the river to Great Egg Harbour, and attended both their meetings,
to a good degree of satisfaction.
On second-day, in the eleventh month, I reached home,
weary in body but comforted in mind, with the reward of sweet peace,
having been enabled to perform the service required of me,
in a good degree of faithfulness and dedication to Him, who had thus called me forth,
and was graciously pleased to go before, and make way.
O blessed forever be his great name,
who continues to be the never failing Helper of his humble dependent children,
who put their whole trust in Him; He has supported through many trials,
and deep probations, yea, sweetened many bitter cups.
May my soul bless, praise and magnify thy great and ever worthy name,
who art God over all, blessed forever!
Be graciously pleased to be with me, the remainder of my days;
strengthen me yet more and more to trust in thy divine arm,
that has been made bare for my help and support!
Many shall run to and fro, and knowledge shall be increased; thus, most gracious God,
thou art fulfilling ancient predictions, thou art sending servants and handmaidens,
to publish the glad tidings of the gospel of peace and salvation.
Be graciously pleased to be with them, go before and make way for them;
enable them to feed thy flock with food convenient, giving meat to strong men,
and milk to babes: keep their eye single to the pointings of thy finger,
and their hearts dedicated to thy commands: be pleased to be mouth and wisdom,
tongue and utterance, and cause thy glory and the knowledge of thee,
to cover the earth as the waters cover the seas.

In the second month, 1808, I attended Woodbury quarterly meeting to satisfaction;
was also at Woolwich and Pilesgrove, and spent a little time with our friends,
but the roads were very heavy, and some other disagreeable circumstances occurring,
we returned home rather too soon.
A heavy storm came on, which we faced, and I took a great cold,
that brought on weakness and many complaints, and reduced me very low in body;
but I was favoured with great sweetness and composure of mind,
being fully resigned to the divine will.
Feeling no desire as to life or death, I could say in truth,
thy will most gracious Father be done; thou knowest what is best to be done; I am thine,
and thou art mine, thou art my all in all; O may my soul cleave fast unto thee.

First month, 1809.
I have been afflicted of late with inward weakness and shortness of breath,
sometimes great difficulty of breathing, but preserved in quietness of mind; yea,
the overshadowing wing of divine love, even as a canopy has covered it.
I feel entirely resigned to the disposal of Him,
whose faith has strengthened me to press through many difficulties,
to perform what I have believed has been required of me, which is now a comfort,
and a support in a time of weakness, when the poor body is much reduced.

When I consider thy abundant mercy and goodness towards me, a poor worm,
how thou hast delivered out of many evils, yea,
preserved out of many snares and temptations,
that have been laid to draw my soul from following thee,
I am led to adopt the language of thy servant, What shall I render unto thee, O Lord,
for all thy benefits towards me?
Oh! may I be fully given up to thee!
In thy presence there is life, and at thy right hand,
are rivers of pleasures forevermore.

Fourth month.
Still continue feeble, and not able to attend our yearly meeting,
though I have much desired to do so for some weeks past, when a little better;
but now feel quite resigned to my present state,
endeavouring to be content in every condition, and resigned to the will of the Most High,
who is I believe weaning me more and more from every pleasant object.
"`Search me, O God, and know my heart; try me and know my thoughts;
and see if there be any wicked way in me, and lead me in the way everlasting.`"

Fifth month.
I am now better and able to attend meetings.
It is truly pleasant to meet with my friends again, after some months absence.
"`How excellent is thy lovingkindness, O God, because thereof,
the children of men put their trust under the shadow of thy wing.`"

Fifth month 14th, 1810, with the unity of our monthly meeting,
I attended Haddonfield monthly meeting, in order to join Elizabeth Foulke,
in a visit to the families of that meeting; Friends uniting with us therein,
we began our visit on the 15th. It was attended with deep baptisms and close exercises,
as dying daily and even hourly, which is needful, in order to be quickened,
and brought to feel with those whom we visit.
We attended their meetings as they came in course, and were in nearly all the families,
amounting to one hundred and thirty.
We finished our visit the evening before our quarterly meeting,
held at Evesham in the sixth month.
Here I parted with my companion in great nearness of spirit,
having travailed and laboured together in unity and gospel fellowship.
I returned home with the reward of peace,
and this language was sweetly the companion of my
mind for many days and nights in my wakeful hours;
Return to the place of thy rest, O my soul,
for the Lord hath dealt bountifully with thee;
which greatly tended to strengthen my mind to bear some close trials.
May the tribute of thanksgiving and praise be given to Him, who lives and abides forever.

In the seventh month, I met with a severe trial indeed,
by the sudden and unexpected death of my oldest son.
I knew not of his illness until late in the afternoon; I went that evening to see him,
and found him nearly speechless, though I believe sensible.
With a look of endeared affection, he grasped my hand, being able to say but very little.
He departed next morning, 2nd of seventh month, aged about thirty-seven years,
leaving a widow and four children.
O the trial such an unexpected event must bring upon a tender mother,
having no opportunity of conversing with him to know his mind,
or to afford any advice or encouragement.
I thought if I could be favoured with an evidence, that all was well with him,
I could freely give him up.
Through divine mercy, I was supported beyond what I could have expected,
and may with some propriety adopt the language of Job, when he said, "`The Lord gave,
and the Lord hath taken away, blessed be the name of the Lord.`"
Thus he sustains the minds of his children and people, who are looking to him,
and calling upon him; he will be unto them as the shadow of a great rock in a weary land;
yea, a covert from storms and tempests; retire there, O my soul,
for there the righteous flee and find safety.

In the first month, 1812, with the concurrence of our monthly meeting,
I joined Margaret Allinson in a visit to the families
of Friends within the compass of Cropwell meeting,
and was favoured with best help; the great Shepherd of his flock was near,
who putteth forth his own and goeth before them.
We got through this little visit to the peace of our own minds, and I believe,
to the satisfaction of our friends.
May the tribute of thanksgiving and praise, be given unto the Shepherd of Israel,
who is worthy forever.
I have been favoured to stay much at home and to enjoy a peaceful mind,
which is a favour indeed, and sometimes to espouse the Master`'s cause,
which at times I feel nearer to me than my natural life.
O may I be preserved, so as never to bring a reproach upon the Truth,
is the desire of my heart.

Our daughter-in-law, Esther Collins, was afflicted with consumption many months,
and often expressed that she did not expect to get well.
She kept up, and attended meetings, until within a few weeks of her close.
After being confined to the room, she appeared much weaned from the world,
and mentioned the satisfaction she had in having attended religious meetings,
particularly some of the last.
One day she told me, she had now gotten through all,
and could give up all but her husband, but said, I hope it will be made easy to me,
which was granted; for in a short time after, she said, Now mother I am willing to go,
I have no choice, no wish, nor will; I see nothing in my way,
and I believe I shall go to rest.
O the comfort it afforded; I said in my heart it is enough; I could ask no more,
but could freely give her up to Him, who had thus made her way easy.
She was very affectionate, and mostly sensible,
and quietly departed on the 10th of the second month, 1811, aged twenty-six years.
"`Blessed are the dead who die in the Lord from henceforth; yea, saith the Spirit,
that they may rest from their labours, and their works do follow them`"--this,
I have no doubt, is the blessed experience of dear Esther,
who is gone from works to a happy reward.

In the fourth month, 1812, I attended our yearly meeting.
It proved a favoured season, wherein the great Head of the Church was pleased to be near,
humbling our hearts and contriting our spirits together,
I think the most so that I ever experienced, taking the meeting through,
more especially the last sitting; our parting was indeed a solemn time,
to be remembered and improved by many.
Friends from different parts attended, whose labours of love were truly acceptable,
many of whom visited our meetings, some before and some after the yearly meeting,
who were as clouds filled with rain that emptied freely upon us.
May their gospel labours be blessed; and we improve so great mercy and favour,
for surely if we do not, great will be our condemnation.
O most gracious Helper, be pleased to prosper thine own work,
to the praise of thy eternal name.

Many indeed are the trials and probations that are to be met with in this world,
and the nearer we live to the Truth, the better we get through them.
In the ninth month I experienced a close affliction
in the death of my dear sister Sarah Wilkins,
who had been many months afflicted with consumption, reduced to a very low state of body,
but preserved in great quietness of mind,
and frequently enabled to give suitable counsel to her family,
and others who came to see her.
She so far recovered, as to attend several meetings, and expressed to a friend,
a desire to attend once more our quarterly meeting at Haddonfield,
which she thought might probably be the last time, as it proved.
There she exhorted Friends in a lively feeling manner,
to faithfulness and diligence in the attendance of religious meetings,
mentioning the great uncertainty of time.
She was taken ill before she reached home, but got there the following day,
and appeared much resigned to her situation, being in great pain.
She frequently supplicated the Father of mercies, to look down upon her,
a poor unworthy creature, and grant patience to bear all her afflictions,
as became a follower of Christ, and not to repine at his dispensations.
Her conflict appeared very great until near the close, when all subsided,
and she departed without a struggle, I doubt not into the arms of divine mercy,
to receive the reward of her obedience.
She was in the fifty-sixth year of her age, a minister about fifteen years,
as near as I can recollect.
Her burial, which was attended by a large concourse of people, was a very solemn season,
at which living testimonies were borne,
and the youth and others invited to follow her example and precepts;
may it be rightly improved.
I sensibly feel the loss of so dear a sister, to whom I was nearly attached,
not only by the ties of nature, but in gospel fellowship;
yet through holy help the separation has been made easier to me,
than I could have expected.

Eleventh month.
My mind has experienced a quiet calm, for a considerable time,
beyond what has been usual for me;
as it is often my lot to pass through gloomy winter seasons,
but as I have endeavoured to abide in patient waiting
and quiet hoping for the return of spring,
I have experienced its return to my unspeakable comfort,
which has fully made up for all my deep trials and strippings;
wherein my soul has been enabled to joy in the Lord,
and rejoice in the God of my salvation.
Being favoured, as before hinted, with a larger portion of divine love and life,
than has often been my experience, I thought, perhaps,
it might be a foretaste of that happy eternity,
which is prepared for those who hold out to the end in well doing,
that I might soon enjoy; but be that as it may,
(the great Jehovah only knoweth) the secret desire of my heart is,
that I may be preserved upon the right foundation, dwelling in humility and fear;
for the more we are favoured,
the more cause of humble gratitude to the Great Giver of all good,
for his abundant mercies.
O may I dwell in humility, and wear it as a garment forever.

I left home with my dear husband to pay a few social visits to some of our friends;
attended Chester meeting on first-day, a favoured season; wherein,
through adorable mercy, my spirit was enabled to worship Him who lives forever;
the meeting ended with thanksgiving and praise unto the Lord Most High,
who is worthy forever.
We visited many under affliction, spent a little time with Rebecca Roberts,
who is about ninety-four years of age; her sight and hearing have considerably failed,
but she appeared to be alive in the Truth--a great
blessing to be preserved green in old age.
On fifth-day attended Evesham meeting to satisfaction,
and on the following evening came home with a peaceful mind, for which I feel thankful.
Return to the place of thy rest, O my soul, for the Lord hath dealt bountifully with thee.
Where is the place of thy rest?
It is in retirement, and prayer to the Father and fountain of all sure mercies,
in watchfulness, dedication, and humble obedience to the divine will.
Here is thy safety, here is the place of thy rest, in times of storms and tempests.

Second month, 1815.
I am now more than sixty years of age, have passed through many heavy afflictions,
yet all in wisdom, best wisdom; for He who knoweth all things,
knows how to deal with us and what is best for us;
and although stripping seasons and deep baptisms are trying to our nature,
yet as they are patiently abode under, they will work for our refinement;
for them that keep the word of his patience, he will keep in the hour of temptation.
This will preserve from murmuring at the dispensations of unerring wisdom and goodness.
Shall not the Judge of all the earth do right?
Yea, verily, he doeth right, and when he sees that our love,
our faith and confidence are fully proved,
(for he will have a tried people that are willing to suffer and wait his time,
our natures being such that we cannot bear all prosperity,)
then he will return with healing in his wings;
his reward is with him, and the poor tried soul is brought to acknowledge, it is enough,
and is richly compensated for all its watchings and fastings.

I left home the 17th of the ninth month, 1815, and attended the Mount meeting,
where my dear friend Martha Allinson met me,
in order to pay a visit to the families of that meeting.
We began our visit in the afternoon, and finished it on the following seventh day,
sitting with the members, and those who attend Friends`' meetings,
and have to acknowledge the goodness of the great Shepherd of his flock,
who was pleased to make himself known by the breaking
of bread from house to house amongst us;
blessed be his adorable name, for his continued mercy and Truth,
thus extended towards his rational creation, unworthy as we are.
We proceeded to Upper Springfield, East-branch, Stonybrook, Trenton, Chesterfield,
Bordentown, Old Springfield, Mansfield, Lower Mansfield, Burlington,
Rancocas and Vincentown;
all these meetings were in a good degree owned by the Great Head of the Church,
and we enabled to labour in his cause to our own peace.
The last meeting was at Mount Holly, on first-day,
large and favoured with the divine presence; it ended in solemn supplication,
thanksgiving and praise, to the Father of all our sure mercies, for his holy help,
and his regard towards us from season to season.
Here I parted from my companion and fellow-labourer, in near unity and gospel fellowship,
and returned home with a peaceful mind; thankful to the Great Helper of his people,
who had enabled me to perform this little visit, in a good degree of faithfulness,
and dedication to his requirings.

First month 7th, 1816.
I have been feeble in body for some weeks past, but quiet in mind,
very much resigned to the Divine will; and in some retired moments,
have been greatly refreshed by the overshadowing wing of Divine love,
still extended to me a poor unworthy creature,
wherein my soul has been enabled to rejoice in the Lord,
and joy in the God of its salvation.

The ways of the Most High are in the deep,
they are past finding out by all the penetration of the finite understanding of man,
uninfluenced by eternal power.
He hath his ways in thick darkness; yea,
he hath many ways to plead with the children of men,
in order to awaken them to a sense of duty to Him, their bountiful Creator.
His love and mercy have been very great, his calls many; yea,
they have been extended many ways in mercy and in judgment.
The inhabitants of this land have been visited in years past with yellow fever,
a disease that greatly baffled the skill of the physicians,
and thinned the people in some places; this disease was sent again and again, in order,
I believe, to humble us.
But what little effect it has had upon the minds of too many; and since,
the typhus fever has raged in divers parts;
great has been the stripping by those pestilential diseases.
Many husbands and wives have been separated,
and in some instances large families of children have been deprived of both parents.
How awful the prospect,
and yet these calamities have not been productive
of the desired effects upon the minds of the people.
Great has also been the calamity of war and bloodshed in our land,
and the distress and havoc it has made in some places.
We have been favoured in this part of the country, only hearing the sound thereof,
compared with what many of our dear fellow creatures have endured.
We are all children of the one Great Parent, and have need of correction,
though we have felt it but lightly.
May we regard the rod, and Him who hath appointed it.
How hath mercy been mixed with judgment, and the sword again sheathed,
and we enjoy peace; but his rod is still stretched over us;
the season has been remarkably cold and dry, with hard frosts,
so that the labour of the husbandman has greatly failed in many instances,
and fields did not yield their usual crops; yea, the land mourned,
and the plants of the fields languished.
O may these things be laid to heart; may they be improved to our advantage,
and considered as the dispensations of unerring wisdom and goodness,
meted out for our correction and improvement.

In the first month, 1817, our dear brother John Collins being from home,
accompanying a Friend on a religious visit, was taken ill with a paralytic stroke,
at a quarterly meeting at Abington in Pennsylvania,
in which he had spoken pertinently to the state of Society.
He was removed from the meeting to a Friend`'s house, where he remained several days,
and appearing to revive a little, was then taken home,
and expressed thankfulness in being brought to his own habitation.
He was much favoured with speech and recollection, considering the nature of the disease;
and in the prospect of death, expressed an entire resignation to the Divine will,
and I doubt not has entered into the mansion of everlasting rest,
there to receive the reward of his labours.
His funeral was largely attended, and proved a highly favoured season.
Being sick myself from home, I was prevented from seeing him, or attending the funeral.
This was a humbling season, as my life was despaired of.
The poor frame was much reduced, but through mercy,
my mind was preserved in humble resignation to the Divine disposal,
and enjoyed a calm where no ruffling breeze nor any thing disturbed;
a favour I greatly wish may be remembered with gratitude,
humble gratitude to the Author thereof.
Although the poor disciples were permitted, when upon the mount with their Master,
to behold his glory, they were not to tabernacle there.
They had to enter the garden, the place of suffering;
for they that would reign with Christ, must also suffer with him.
It is indeed a great lesson to learn to be content, willing to suffer or to reign,
to be abased or to abound,
and is what I fear I am too deficient in --but an imperfect scholar.

After near six weeks confinement, I was brought home on a bed,
and was favoured gradually to recover, so as to get to meeting,
and there through Divine mercy, to meet with Him,
who promised to be with the two or the three, that should meet in his name;
and at seasons, humbly to worship and adore Him who lives forever,
and is worthy to be worshipped by the whole creation, world without end.

Ninth month.
I am feeble and much reduced in body.
It looks most likely the solemn dissolution is approaching,
wherein the dust must return to the dust,
and the immortal part be centered in another state of being, in which I feel resignation.
My greatest desire is, that I may so live and so walk in humility, watchfulness and care,
as not to offend in thought, word, or deed,
but fully and cheerfully submit to every dispensation of unerring Wisdom and Goodness,
who knows how to deal with his children, and what food is most convenient for them.
Thou, O most gracious and holy Helper, knowest all things; thou knowest that I love thee,
and that I long to serve thee, in uprightness and singleness of heart;
but alas! what am I, a poor weak creature, entirely unable to do any good thing,
or even to think a good thought, without thy holy aid.
Be pleased in mercy to be near, and preserve me by the right hand of thy righteousness.
O thou who hast fed me all my life long, and who hast redeemed me from many evils,
be pleased to cause the Angel of thy presence, to encamp round about my poor tabernacle;
and strengthen me, holy Father, to render unto thee that which is thy due,
even the tribute of thanksgiving and praise, with thy dear Son, our blessed Redeemer;
to whom be honour and praise, now and evermore.

Fourth month, 1818.
I was favoured to attend our yearly meeting, which proved an instructive season,
many Friends from different yearly meetings being there;
who were clothed with authority and power to publish the glad tidings of peace and salvation:
encouraging the humble in heart to pursue the path of virtue and dedication;
also labouring to arouse the careless and lukewarm to more diligence.
The youth were invited to enlist under the government of Christ,
and thereby experience his banner over them to be love.

In the fifth month, I informed Friends at our monthly meeting,
of a prospect which I had had for a considerable time, of paying a visit to the meetings,
within the compass of Salem quarter, also the families of Friends, and others,
who make profession with us at Pilesgrove, and to those residing at Cape May,
with which they united; my dear friend Abigail Haines gave up to go with me.
We attended Salem quarterly meeting, accompanied by our kind friend Josiah Reeve;
it was owned by the great Head of the Church.
We then proceeded to Greenwich, Alloways Creek, Penns Neck, and Mullicahill,
all to a good degree of satisfaction.
On fifth-day, attended the monthly meeting at Pilesgrove, where we produced our minutes,
and opened our prospect of visiting the families of that particular meeting,
with which they freely united: Sarah Scull joined in the visit,
of whose company I was truly glad.
After meeting Josiah Reeve left us, and returned home,
and we proceeded on our visit from house to house.
There appeared generally great openness to receive us, and the Author of all good,
was pleased in his abundant mercy, to be mouth and wisdom,
tongue and utterance to my humbling admiration,
and I have to believe it was a fresh visitation to many.
May the praise be given to Him alone to whom it is due,
for his continued goodness and love to the workmanship of his holy hand,
unworthy and forgetful as we are.
After completing the visit,
which we did not accomplish before the ensuing monthly meeting,
we set off for Maurice River, taking a few families residing on the way,
where we parted from dear Sarah Scull.
Attended that meeting on first-day, which was in a good degree satisfactory.
Afternoon we rode to Cape May,
and the succeeding morning began the visit to the families there,
which we completed on fourth-day morning.
Attended their meeting, which is composed of but few members,
and some of them I fear are dwelling too much on the surface, not willing to dig deep,
in order to lay their foundation sure, on Christ Jesus the Rock of ages.

After meeting rode to Dennis`' Creek,
where we had a satisfactory opportunity in a family descended from Friends;
on sixth-day attended Maurice River monthly meeting, first-day Maurice River Neck,
and the following morning proceeded to Upper Greenwich,
which we attended to good satisfaction.
On fifth-day at Woodbury monthly meeting, deeply exercising in the forepart,
but through close attention and labour found some relief.
In company with several Friends, we visited the county poor house,
as we had that in Salem county.
Truly it is affecting to see so many of our fellow beings,
labouring under afflictions of various kinds,
though they appeared to be comfortably provided for.
This was our last visit, which through adorable mercy, proved a memorable season;
we were comforted together, and the great Author of all our blessings,
was praised for his lovingkindness and Truth continued to us.
Next day we got to our own monthly meeting, returned our minutes,
and gave some account of our labours, which appeared satisfactory to Friends,
and arrived at home with a peaceful mind.
In looking over this little journey, it affords a comfortable sensation,
except a few omissions, which caused some uneasiness of mind,
but I hope they will be looked over by my good and gracious Lord and Master,
as they did not originate from wilful disobedience, but rather weakness of body and mind,
which was then my clothing.
It is humbling to remember the kindness and attention
of Friends to me in my feeble state,
as I was very unwell most of the time I was from home;
this favour I received as from the Divine hand.

How comfortable are our feelings when we can breathe
the language of "`Glory to God in the highest,
peace on earth, and good will to men;`" the language of glory, honour and praise to Him,
who lives and abides forever; to feel sweet peace of mind,
and love to all our fellow creatures; no grudge, no hardness nor resentment,
but all love and concord.
My soul rejoices under a renewed sense thereof, and acknowledges that sweet is thy voice,
and thy countenance is comely.
Thy name is as precious ointment poured forth, therefore do the virgins love thee;
the pure in heart, those who have none in heaven besides thee,
nor in all the earth compared with thee; those who by deep indwelling of soul,
are instructed in the mysteries of thy kingdom.
Thy ways, O Lord, are in the deep,
they are past finding out by all the wisdom of finite man.
Those who are instructed in the knowledge of thy blessed Truth,
are led at seasons to acknowledge, that "`Great and marvellous are thy works,
Lord God Almighty, just and true are all thy ways,
thou King of saints;`" thou who art King immortal, invisible and all glorious,
glorious in thyself, and glorious in the Son of thy bosom; to whom be honour,
thanksgiving and praise, now and evermore, saith my soul.

First month, 1820.
In company with my friends Joshua Stokes and wife, and A. Haines,
I visited the monthly meetings of Byberry and Horseham.
At this meeting things were delivered in a close line,
but in that love which seeketh to restore, in which I found peace.
The weather was pleasant when we set out, but it afterwards became cold, froze the river,
so that we were obliged to ride to Trenton, in order to cross the bridge.
Reached home cold and weary, but quiet in mind,
and thankful that way had opened to pay this little visit to my Friends,
which I had long thought of.

On the 5th of the second month, as Ann Edwards and my sister-in-law Esther Collins,
accompanied by another female and a man Friend to drive them,
were attempting to cross the Delaware on the ice in a wagon, it proved too weak,
though several had crossed before them, and when little more than half over,
the horses broke through.
The two Friends who sat front leaped out, the woman Friend upon the broken ice,
and was prevented from sinking, by the exertions of the other,
till assistance came and helped her out of the water.
The horses, wagon, and the other two dear women, Ann and Esther,
were soon out of sight under the ice.
Great exertions were used to find them, but in vain.
After being in the water twelve days, dear Esther was found in the wagon-body,
opposite Philadelphia, was taken home, and buried the next day.
It was remarked she looked more like a person asleep than a corpse; her funeral was large.
Dear Ann`'s corpse was found on the Pennsylvania shore,
having been in the water about seventy days, and was brought to her brother`'s,
and buried in Friends`' burying ground at Chester.
It was a great satisfaction to their friends,
that the bodies were recovered and decently interred.
But, Oh! the loss of two such worthy women,
not only to the meetings of which they were members,
but to the neighbourhood where they lived!
Ann being a minister,
appointed many meetings amongst those who were not members of any Society,
and visited many of them in their families, in which service, Esther who was an elder,
mostly accompanied her.
Ann being very weakly, expressed she thought her day was short,
and wished that her day`'s work might keep pace with the day.
They were often engaged in visiting the sick and the afflicted,
and left home in order to visit some of their Friends under affliction,
and attend a meeting or two, when the solemn event took place;
that it may be justly said, in their lives they were united,
and at their death they were not divided.

It was in the evening I heard the mournful intelligence,
which was a very great shock indeed.
My health being feeble, I soon retired to bed, expecting to pass a sleepless night,
but endeavouring to get my mind composed, at length I was favoured to feel a quiet calm,
and through faith, to believe they were safely landed on that happy shore,
where sorrow ceases, and troubles are no more.
I then fell asleep, and had a comfortable night`'s rest, which I esteemed a favour.

Third month.
It has been a stripping time to me of late.
In the twelfth month last, my only sister Bathsheba Moore, who lived at Red Stone,
departed this life after a long and tedious illness,
which she bore with Christian patience, quietly waiting for the final close.
In the second month, my sister E. Collins died,
who was more like a mother than a sister by marriage.
I seldom met with her, but she had a word of comfort or advice to me,
like the good scribe well instructed, bringing forth out of the treasury,
things old and new.

In the third month, my brother J. Ballinger deceased; his bodily affliction was great,
and he appeared to be under deep exercise of mind, on account of his future welfare;
I have a comfortable hope, he was favoured to make his peace with his Maker in time.

My state of health being feeble, these losses were no doubt more sensibly felt;
I was the only one left of our family, and as I was sitting pensively alone,
reflecting on my stripped state, the language of the Psalmist came fresh into my mind;
"`When my father and mother forsake me, then the Lord will take me up.`"
This expression was comforting, and I was made renewedly sensible,
that although I was thus stripped, without father or mother, brother or sister,
yet I was not forsaken by the Father and fountain of all our sure mercies,
who in condescending love, was pleased to comfort my mind, yea,
to favour with his holy presence; that I was led humbly to commemorate his goodness,
his love and mercies, extended from season to season,
and secretly to implore the continuance of his blessing through time,
that I might not become a dry and withered branch.
O it is a blessed state to be preserved alive in the Truth,
bringing forth fruit in old age; fruits of holiness of life,
fruits of dedication of heart to the will and service of God;
that this may be my happy experience, is the breathing of my soul.

My health continued feeble through the summer, though for the greater part of the time,
I was able to attend our meetings,
and at seasons favoured with the overshadowing wing of Divine love,
wherein my cup has been made to overflow; and in the aboundings of gospel love,
was enabled to call and invite others, to come taste and see how good the Lord is, yea,
to acquaint themselves with God, and be at peace.
Towards fall, my health rather increased,
so that I was at our quarterly meeting in the ninth month,
which was an instructive season, many Friends from different meetings attended,
and the Lord was pleased to favour with his divine presence.

I was again confined by sickness,
in the forepart of which I was not so favoured with the divine presence,
as in some other seasons of indisposition, which I was enabled to bear with patience,
knowing that it is good for us to be abased, as well as to abound.
At length he who ordereth all things rightly,
was pleased to return as with healing in his wings,
and my soul rejoiced in the God of its salvation; and in some moments of retirement,
I was qualified to bow as at his holy footstool,
and implore the continuance of his mercy and protection,
through the few remaining days of my life,
and finally receive me into the realms of everlasting bliss.
At these seasons, my dear children were brought near to my best life,
with desires that they might become the Lord`'s children.
These are all taught of him, and great is the peace of his children.
O that there may be a willingness in every heart, to be guided by him,
who leads into all truth, and preserves out of all evil.
There are many snares and temptations in the world,
which we poor creatures are liable to fall into,
unless we look to him who is the great Preserver of men,
begging the blessing of preservation, that we may be kept from evil,
and do that which is right in the divine sight.

Fourth month, 1821.
My health is better, so as to be able to attend meeting;
it is comfortable to sit with my friends again.
I feel very desirous that I may keep my place,
that I may be just what the Almighty would have me to be,
that his will may be done in me, by me, and through me.
These lines have been so sweetly revived when in a feeble state,
and feeling a peaceful calm and quiet, I thought I could with propriety adopt them,
as the present state of my mind; viz.

"`How are thy servants blest, Lord,

How sure is their defence;

Eternal wisdom is their guide.

Their help, Omnipotence.`"

How comfortable, when we can rightly number and appreciate our blessings,
knowing our place of defence to be the munitions of rocks, bread to be given us,
and our water to be sure; receiving all from the Divine hand,
and experiencing that wisdom which is from above,
and is profitable to direct in all our movements, to be tongue and utterance,
and strengthening us to resign all up to his most holy will,
humbly trusting in the divine arm.
May this be more and more my happy experience through the remaining days of my life,
that when the evening comes, the work may be so completed,
that I may receive the answer of "`Well done good and faithful servant,
enter thou into the joy of thy Lord.`"
O blessed change, glorious triumph, to be admitted into the mansion of eternal rest,
there to sing praises unto the most High God, and the Lamb,
who is worthy forever and ever; which is the sincere breathing of my spirit.

+++[+++The following is an extract from a letter written to a Friend,
on recovering from illness, dated Twelfth month 19th, 1821.]

May we, my dear friend, patiently submit to every dispensation of divine Providence,
and endeavour to improve under it;
for all things work together for good to them that love and fear the Lord.
We have our night seasons, and our winter seasons, but as we abide in patience,
we shall experience the dawn of the day, and the return of the spring,
to our comfort and rejoicing.
I greatly crave thy welfare and firm establishment upon that sure foundation,
Christ Jesus, the Rock of ages;
and that thou mayest experience thy wilderness to become as Eden,
and thy parched ground as the garden of the Lord,
and be enabled to bring forth fruit to the praise and honour of the great and good husbandman,
who hath done so much for us; who loved us before we loved him.
At seasons when favoured to commemorate his goodness,
his love and mercy to me a poor unworthy creature, I am led to adopt the language,
"`What shall I render unto thee, O Lord, for all thy benefits towards me?`"
They are great, they are many.

+++[+++Twelfth month 7th, 1823.
To the same she writes again, from which the following is extracted; viz.]

I feel near sympathy with thee and my dear friends in that city (Philadelphia),
and the desire of my heart is for your preservation.
The name of the Lord is a strong tower, the righteous run thither and find safety.
Yea, as the shadow of a great rock in a weary land, hath he been to many of us,
in storms and heavy trials, when the waves and billows have run very high indeed.
It is a great consolation to reflect, that bounds are set; so far shalt thou go,
but no further.
Oh! may we dwell in watchfulness and prayer to the
God and Father of all our sure mercies for preservation.
We have this assurance, "`The Lord knoweth them that are his.`"
And it is through tribulation, the righteous enter the kingdom of heaven.
This encouraging language just now salutes my mind, "`Fear not little flock,
it is your heavenly Father`'s good pleasure to give you the kingdom.`"

I think I may safely say, the older I grow, the more I feel true love towards my friends,
and a greater desire for the prosperity of Truth and righteousness,
which I consider a favour in this day of commotion and division;
to feel that which enables to breath, "`Glory to God in the highest, peace on earth,
good will to men.`"
It was for the divisions of Reuben, there was deep searching of heart.
Oh! that this might take place amongst us,
for I believe there has not been a time since we were a people,
that there was greater need of deep searching of heart; yea,
deep indwelling of soul before the Divine Majesty, imploring his aid and preservation,
that we may become faithful standard bearers, and upright pillars in his house.

First month, 1825.
I am more than seventy years old; an age I did not expect or desire to attain unto,
but thus it has proved, my days have been lengthened out in best wisdom, no doubt,
to take care of my dear husband in his afflictions,
having been in poor health for upwards of three years,
which he has been favoured to bear with patience and Christian fortitude.
At one time after a season of silent retirement, he expressed to me,
"`I think I have never been more willing to put off this poor tabernacle of clay,
than at the present time, though no merit of mine.
In looking over I can see many imperfections through life,
that I have nothing to trust in, nothing to build my hopes of salvation upon,
but the mercy of a gracious and bountiful Creator, and the merits of a glorious Redeemer,
who laid down his precious life for us, paid the ransom of his own precious blood,
and has ascended up on high, and sitteth at the right hand of the Divine Majesty,
making intercession for poor fallen man.`"
He spoke in such a tender feeling manner, I was moved with gratitude,
and think it worthy to be penned down.

The latter end of the second month, our son-in-law, Samuel Thorn, departed this life,
after a tedious afflicted confinement of near three months;
neither my husband nor myself was able to attend his funeral.
It was trying, as I felt much for the family, having buried two daughters, young women,
sometime before, and I was not able to go to see them, nor attend their funerals.
As these things lay upon my mind, the following lines sweetly presented:

"`What cannot resignation do?

It wonders can perform;

That powerful charm, Thy will be done?

Can lay the loudest storm.`"

This had a tendency to settle my mind, in humble resignation to the divine will.
I then remembered I had paid him a visit in his sickness,
had a favoured opportunity with him, and part of the family, when I took leave of him,
as not expecting to see him again, so that my mind enjoyed a perfect calm.

I think I have scarcely ever experienced those expressions of the apostle nearer realized,
than in my present feeble state; when he said, "`For me to live is Christ,
but to die is gain.`"
As the will becomes fully subjected,
and every thought brought into the obedience of Christ, when his will becomes ours,
we have no will contrary to his divine will; then may we with propriety express,
To live is Christ, to die is gain; great gain to put off mortality,
and to be clothed upon with immortality, and eternal life.
When the mind is thus centered, we are enabled to acknowledge,
that sweet is thy voice and thy countenance is comely.
Thy name is as precious ointment poured forth, therefore do the virgins love thee,
the pure in heart, those who are weaned from every other beloved,
and their affections set upon the Beloved of souls.
These experience in truth that one hour in thy courts, or presence,
is better than a thousand; they can testify that thy name, which is thy power,
is as precious ointment, a savour of life unto life,
which strengthens to offer the tribute of worship, adoration and "`praise,
unto the great Jehovah, who is worthy,
with his beloved Son our blessed Saviour and Redeemer, who paid the ransom for us,
and who is one with the Father, to whom be glory, honour,
thanksgiving and high renown forevermore.
Amen.

Many are the trials and afflictions, that await us in this probationary state,
agreeable to the declaration of our blessed Saviour; who said,
"`In the world ye shall have tribulation, but be of good cheer,
I have overcome the world.`"
In the eighth month, 1825, we met with a close trial, in the death of our son Ezra,
who lived with his brother-in-law.
When I heard he was sick, my impression was, that he would not get well,
and I believed it right for me to give him up to Him,
who has a just right to dispose of us, as he sees best.
My business was, to beg for resignation to the divine will,
and that he might be prepared for the mansion of everlasting rest.
We went to see him, found him very ill, and stayed with him until the next day afternoon;
he inquired of his father, if we expected to go home; he replied,
we did if he was willing; he answered I have a choice in your staying,
but if you think best of going, it must be so.
When I parted from him, he took his leave of me in a very affectionate manner, and said,
"`Mother, I think I shall not see thee again.`"
My reply was, "`Well, my dear, if we do but meet in heaven,
that will be the crown of all.`"
He said, "`Oh yes, mother,`" and spake as if he felt what he said.
He saw I was feeble and tried, and showed his tenderness and sympathy for me,
in requesting a friend to take hold of my arm, and help me downstairs.
He departed on the following evening, in the twenty-fifth year of his age,
without sigh or groan, so quietly,
that those who sat by him could scarcely perceive when he ceased to breathe.
He was a very dutiful son; from the best recollection I have,
I do not remember he ever disobeyed me.
His corpse was brought home, and at the funeral a lively testimony was borne,
which had a tendency to strengthen my belief that all was well--that
he was admitted into the mansions of everlasting rest.
In a few months after, two of the daughters of my son Abraham Mason deceased,
the first a blooming youth as it is common to see,
taken out of time with a few days sickness,
which greatly affected her sister who was in poor health:
and she did not survive but about three months.

+++[+++After narrating; the circumstances attending the death of her son Ezra,
in a letter to a friend, dated eleventh month 11th, 1825,
she mentions a loss incurred by a son-in-law,
and the reflections which passed through her mind on those occasions,
in the following manner: --

"`A fire caught in an old building near the house,
that burnt nearly all their out buildings, which were very valuable,
with the hay and grain in them, except a little Indian corn.
I got there when it was all in flames; such a scene I never beheld;
the house with its contents was saved, which is a great favour indeed;
it is cause of gratitude, humble gratitude to the Author of all our blessings.
When the buildings were all in flames, I remembered the expressions of Job,
when stript of his substance and his children also; '`The Lord gave,
and the Lord hath taken away, blessed be the name of the Lord.`'`"

In the same letter she proceeds as follows:--

"`I often feel anxious for thee,
greatly desirous that thou mayest be preserved upon the right foundation,
in this trying day, wherein the foundations of many are shaken,
and they are denying the Lord that bought them,
counting the blood of the Covenant as an unholy thing.
Sorrowful it is indeed, that such a division has taken place;
such a great departure from the faith once delivered to the saints,
and embraced by our predecessors.
But through mercy there are some whose faith is not shaken;
of which number I hope thou art one.
It is in my heart to say, hold fast that which thou hast;
that no one take thy crown from thee.
The crown is to be obtained at the end of the race, and they that hold out to the end,
are to be saved with an everlasting salvation.
The apostle expressed, '`he had fought a good fight, had kept the faith,
and that henceforth there was laid up for him a crown
of righteousness.`' It is a sifting time indeed.
I have often remembered those expressions of our blessed Redeemer,
where he told his followers, '`that Satan was desirous to have them,
that he might sift them as wheat; but I have prayed for thee Peter,
that thy faith fail not.`' O may we walk worthy of the prayers, intercessions,
and preservation of a gracious and bountiful Mediator and Redeemer,
is the desire I now feel while I am writing.`"

In the second month, 1827,
my dear husband departed this life in the seventy-fifth year of his age,
after a long and tedious confinement and affliction of near five years and a half.
His suffering at times was very great,
which he was favoured to bear with much Christian fortitude and patience.
He attended meetings as long as he was able to go,
and encouraged my going whenever I was easy to leave him,
and frequently mentioned his love for his friends.
At different times he said, "`the faith in which I have lived,
is that faith in which I hope to die,`" and I fully believe he did.
I never perceived the least change in his sentiment,
and believe his departed spirit is now at rest in the arms of Redeeming Mercy;
this is my comfort, my great consolation.

Our daughter, Lydia Stokes, was very ill at the time of her father`'s death;
she grew better, so that there was some hope of her recovery,
but being attacked with another complaint, she died on the 4th of the fifth month, 1827,
in the fortieth year of her age, leaving eight children.
Hannah Collins departed this life the 30th day of the following month, aged forty years.
Her health had been declining for some years, though she mostly attended meetings,
and was a good example therein.
At one time, after raising some blood, she said to me, "`O mother,
what a favour to feel so composed and quiet at such a time.`"
These discharges of blood from the lungs, though frequent,
were not very large until the last.
She had retired to bed as usual, and about twelve o`'clock,
it appeared a blood vessel ruptured, and she was soon suffocated,
not being able to say much that could be understood.
I did not get up into her chamber until she was nearly gone,
A few short expressions indicated her state of preparation for the solemn event,
"`Give me up,`" "`Take care of the children,`" "`Sweet
Jesus receive my spirit,`" "`All will be well.`"
I considered her a precious woman, and an affectionate daughter.
If I had been been own mother, she could not have been kinder to me.
We lived together more than thirteen years,
and there never was an unpleasant word passed between us;
this affords great satisfaction to my mind at this trying season.
Oh, the loss we have felt, not only in our family, but in the Society; there is, however,
a consoling hope, that our loss is her everlasting gain, that all is well indeed.

The 2nd of the fourth month, 1828, my son, Abraham Mason,
departed this life in the fifty-third year of his age,
after a long and tedious consumption,
which through adorable mercy was sanctified to him for good.
A profitable season, wherein he became instructed in the school of Christ,
and was enabled to bear his affliction with Christian fortitude.
Being favoured with his understanding,
he took leave of his wife and children in an affectionate manner,
and quietly departed without sigh or struggle.
In the tenth month following, one of my granddaughters in her twenty-third year,
was removed by death; she appeared to be comfortably settled with a kind husband;
but how uncertain are all things here below; nothing worth setting the mind upon.
I have mentioned some of my close trials,
not in a disposition of murmuring--no --for the language of my heart often is,
Shall not the Judge of all the earth do right?
most assuredly; his ways are in wisdom, he knoweth what is best for us,
what food is most convenient; they are removed from the troubles to come,
and it is our duty to be resigned to his will.

It is a trying time in our Society; many have gone off, set up meetings of their own,
and yet continue to be troublesome at our meetings; that it is a trying day,
a day of mourning, wherein the language of my heart has often been,
"`Oh! that my head were waters, and mine eyes a fountain of tears,
that I might weep day and night for the slain of the daughter of
my people;`" a time wherein the mournful exclamation may be adopted:
"`How are the mighty fallen;`" yea, "`how is the gold become dim,
and the fine gold changed, the beautiful sons of Zion, and daughters too,
have become as earthen pitchers;`" brittle,
and not fit to bear the inscription of holiness unto the Lord, and his Christ;
for holiness becomes God`'s house forever.

Third month, 1829.
I am now quite feeble, and it looks most likely "`my departure is at hand.`"
Be that as it may, the divine will be done.
I feel neither wish nor will,
and may with some degree of propriety adopt the language of the apostle,
"`I have fought the good fight, I have kept the faith;
henceforth there is laid up for me a crown of righteousness,
which the Lord the righteous Judge will give me at that day, and not to me only,
but unto all them also, who love his appearance.`"

Through the summer, I have been in better health,
so as to attend our quarterly meeting in the sixth month,
and mostly our own particular meetings, and at seasons,
a little to advocate the great Master`'s cause.
Eleventh month, mostly confined to my room, but favoured with a quiet and composed mind,
wherein I have been enabled to breathe, "`glory to God in the highest, on earth peace,
good will to men,`" to breathe, glory, honour,
thanksgivings and praise unto the great Jehovah, who with his dear Son,
our blessed Redeemer, is worthy forever.
Oh! the preciousness of the Truth; how it strengthens and supports the mind,
that I may say with the poet,

"`My life, if thou preserv`'st my life,

Thy sacrifice shall be:

And death, if death shall be my doom,

Will join my soul to thee.`"

O blessed union and communion,
to join the heavenly host in singing praises and hallelujahs,
unto the Lord God and the Lamb, who is worthy forever.
Amen.

"`If ye love me keep my commandments,`" said Christ our Lord.
"`This is my commandment, that ye love one another, as I have loved you.
Greater love hath no man than this, that a man lay down his life for his friends.
Ye are my friends, if ye do whatsoever I command you.`"
Oh! the excellency of this love; it does away all malice, hard thoughts or resentments,
and brings us where we can rejoice in the comfort and happiness of each other.
In a degree of this love,
I have been led secretly to intercede for the whole human family,
that all might come to the knowledge of the Truth, as it is in Jesus,
and be saved with an everlasting salvation.

+++[+++This appears to close the memorandums of our beloved friend.
In the sixth month, 1830, she addressed the following note to her Friends,
at their quarterly meeting at Evesham.

Sixth month 15th, 1830.

My love affectionately to Friends at our quarterly select meeting.
Although I am feeble in body,
am sound in faith and love to our glorious Redeemer`'s cause.

Elizabeth Collins.

Reports having been circulated that she had changed her principles
and adopted those which had latterly been spread amongst Friends,
it became a matter of much concern to her; and after weighing the subject several weeks,
she believed it proper to draw up a declaration of her faith,
to refute the misrepresentation, and for the use of those who survived her,
of which the following is a copy.
She afterwards mentioned that the completion of it was a relief to her mind.

"`As my health continues feeble, but being favoured with a sound mind and memory,
an impression has repeatedly revived on my mind, as it is a day of misrepresentation,
that it would be right to leave something to show that my faith is not changed;
that I have no unity with that disorganizing spirit, that has caused the separation,
which has taken place in our religious Society.
In the faith in which I have lived, in that faith I desire to die.
I hereby testify, that I am no Hicksite,
but a firm believer in the divinity and offices of our Lord and Saviour Jesus Christ;
that he was the true Messiah, born of the Virgin Mary,
and that he came a light into the world to enlighten mankind universally;
that he was the one great propitiatory sacrifice and atonement for all;
that he laid down his life, paid the ransom of his own precious blood,
for our salvation and redemption; and when his mission here on earth was finished,
ascended up on high, and now sitteth on the right hand of the Divine Majesty,
making intercession for poor fallen man; and that he is our holy high Priest,
and Advocate with the Father, even his own beloved Son; to whom belong glory and honour,
adoration, thanksgiving and praise, both now, forever, and forevermore.
Amen.

Dated Eleventh month 20th, 1830.

Elizabeth Collins.

In the twelfth month she again addressed her Friends at their quarterly meeting,
with this salutation of love, by which she evinced a continued interest in their welfare,
and a humble, patient waiting for the coming of her Lord.

My love is affectionately to Friends at our quarterly meeting at Evesham,
and may inform that I am endeavouring patiently to wait
and quietly to hope for a blessed and happy change,
when He who orders all things in wisdom, sees that it is enough; and may further add,
finally, beloveds, farewell; be of good comfort, be of one mind; live in love,
and the God of love and peace be with you.
Amen.

Elizabeth Collins.

Fourteenth of twelfth month, 1830.

From the summer of 1829, till the autumn of the following year,
bodily infirmity and disease confined her very much at home.
It was seldom she got to meeting in that period,
but often expressed a desire to be with her Friends in their solemn assemblies,
for the performance of divine worship, and made exertions in going,
when others would have deemed it more proper to keep in the house.
During the confinement,
she was visited by many Friends to whom her conversation was interesting and instructive.
Being an example in plainness and moderation, her mind was often under much exercise,
on account of the many extravagancies which have crept into the Society,
particularly in entertainments at marriages;
and the deviations from the simplicity of our forefathers,
in dress and the manner of living.
She frequently expressed it was her conviction,
there must be a return to first principles,
and to the plain self-denying manners which they exhibited.

The separation in our religious Society,
united as the members once were in the faith and fellowship of the gospel of Jesus Christ,
was a subject of deep concern to her feeling mind.
When in the company of any of those who had seceded,
she demeaned herself towards them as becomes a Christian believer, kind and courteous,
yet undeviating in maintaining the Truth as it is in Jesus,
against the unsoundness of principle,
and the disaffection which had unhappily overtaken them.

With those who kept their ground, labouring together for the preservation of the Society,
amidst numerous difficulties, both new and keenly afflicting,
she desired to partake in the fellowship of suffering,
and to strengthen their hands as she might be enabled, frequently saying,
her Friends never felt nearer to her.
In a conversation with one of them who visited her,
she remarked in substance respecting the secession;
I am much retired from the Society of my dear Friends,
but am not without feelings of near sympathy with them, in their tried situation,
in bearing their testimony against this disorganizing spirit.
I have had much time to reflect, and to weigh those things in my own mind,
and my faith is in no wise shaken, but confirmed in a full persuasion and belief,
that their principles must fall; they cannot stand; they are built upon the surface;
but I am not prepared to say when that may be;
it is all within the controlling power of divine Providence.

In the ninth and tenth months of 1830, her health a little recruited,
so as to admit of attending the meeting to which she belonged pretty generally,
where her company imparted comfort and encouragement to her Friends,
who from her advanced age and frail system, could but anticipate the removal,
in a short period, of one who was a mother in Israel amongst them.
Her ministry on these occasions was very impressive,
both on account of the clearness of the doctrine, and the authority which accompanied it,
being delivered with a distinct and audible voice, notwithstanding her reduced condition.
She preached Christ Jesus, and him crucified,
as the means of redemption from a fallen state,
and from the power of the prince of darkness,
in refutation of the unsound notions on these points,
propagated by those who have seceded from us.

From this period she was confined to the house,
her feeble frame gradually giving way to the influence
of frequent indisposition and natural decay.
On one occasion speaking of her debilitated state,
and the improbability of getting out again, her daughter replied,
it was the case the preceding winter when she expressed the same opinion,
but had nevertheless recovered, so as to meet with her Friends.
She, however, now confidently said, she should never see the meetinghouse again,
and "`when the close comes, all will be well.`"

In a visit made by one of her junior friends,
who considered it a privilege to be with her,
and witness her patient submission to the Divine will,
the liveliness of her spirit in old age,
and the assurance of that blessed hope which reaches within the veil, she observed,
"`I am here yet; may I be favoured with patience to the end.
I feel as one waiting the change,
and believe the day`'s work has been done in the day time.`"
To the same friend at another period;
"`Time is not tedious--I am favoured with a calm mind,
and though the poor body suffers much at times, I dare not murmur or complain.`"

In the last few weeks she conversed very little,
appearing to be almost entirely abstracted from worldly objects,
and her mind collected into a state of waiting and fixedness upon the Lord,
that she might be ready at his coming.
About a week before the close, she was attacked with a pleuritic affection,
which at times occasioned much pain and suffering, and prostration of strength.
But having been long taught and disciplined in the school of Christ,
she maintained the same patient, enduring spirit under suffering to the end,
being clothed with that love and serenity, which gave evidence to those around her,
that it was a participation of those joys, into the full fruition of which,
we believe she was permitted to enter.
She quietly departed on the 1st of the second month, 1831,
in the seventy-seventh year of her age.
